In [ ]:
# @title 🛠️ Verify & Load GrievanceIQ Datasets {display-mode: "form"}
import os
from google.colab import drive

# Mount Google Drive to access the shared folder files
try:
    print("Mounting Google Drive...")
    drive.mount('/content/drive')
except Exception as e:
    print(f"Could not mount Google Drive automatically: {e}")
    print("Please ensure you run this cell and authenticate when prompted.")

# Define the target files we need to locate
target_files = [
    'grievanceiq_complaints_multilabel_6000.csv',
    'grievanceiq_relationship_pairs_16000.csv',
    'grievanceiq_department_mapping.csv',
    'grievanceiq_knowledge_graph_relations.csv',
    'grievanceiq_workflow_task_dependency_rules.csv'
]

# Let's search the common Drive paths or local environment to find where these files reside
found_paths = {}
search_dirs = ['/content/drive/MyDrive', '/content']

for search_dir in search_dirs:
    if os.path.exists(search_dir):
        for root, dirs, files in os.walk(search_dir):
            for file in files:
                if file in target_files:
                    found_paths[file] = os.path.join(root, file)

print("\n--- Verification Results ---")
for f in target_files:
    if f in found_paths:
        print(f"✅ Found: {f} -> {found_paths[f]}")
    else:
        print(f"❌ Missing: {f} (Please upload this file or make sure it is in your Drive)")

Mounting Google Drive...
Mounted at /content/drive

--- Verification Results ---
✅ Found: grievanceiq_complaints_multilabel_6000.csv -> /content/drive/MyDrive/GrievanceIQ Dataset/grievanceiq_complaints_multilabel_6000.csv
✅ Found: grievanceiq_relationship_pairs_16000.csv -> /content/drive/MyDrive/GrievanceIQ Dataset/grievanceiq_relationship_pairs_16000.csv
✅ Found: grievanceiq_department_mapping.csv -> /content/drive/MyDrive/GrievanceIQ Dataset/grievanceiq_department_mapping.csv
✅ Found: grievanceiq_knowledge_graph_relations.csv -> /content/drive/MyDrive/GrievanceIQ Dataset/grievanceiq_knowledge_graph_relations.csv
✅ Found: grievanceiq_workflow_task_dependency_rules.csv -> /content/drive/MyDrive/GrievanceIQ Dataset/grievanceiq_workflow_task_dependency_rules.csv

In [ ]:
# @title 📥 Load GrievanceIQ ML Training Datasets

import pandas as pd
import os

DATA_DIR = "/content/drive/MyDrive/GrievanceIQ Dataset"

complaints_path = os.path.join(
    DATA_DIR, "grievanceiq_complaints_multilabel_6000.csv"
)

relationships_path = os.path.join(
    DATA_DIR, "grievanceiq_relationship_pairs_16000.csv"
)

# Load datasets
complaints_df = pd.read_csv(complaints_path)
relationships_df = pd.read_csv(relationships_path)

print("✅ Complaints dataset loaded")
print("Shape:", complaints_df.shape)

print("\n✅ Relationship pairs dataset loaded")
print("Shape:", relationships_df.shape)

print("\n--- Complaint Columns ---")
print(complaints_df.columns.tolist())

print("\n--- Relationship Columns ---")
print(relationships_df.columns.tolist())

print("\n--- Complaint Sample ---")
display(complaints_df.head())

print("\n--- Relationship Sample ---")
display(relationships_df.head())

✅ Complaints dataset loaded
Shape: (6000, 20)

✅ Relationship pairs dataset loaded
Shape: (16000, 17)

--- Complaint Columns ---
['complaint_id', 'issue_id', 'complaint_text', 'issue_types', 'latitude', 'longitude', 'location_name', 'timestamp', 'urgency', 'responsible_departments', 'is_clustered_issue', 'source_type', 'road_damage_flag', 'roadside_flooding_flag', 'water_leakage_flag', 'electric_pole_flag', 'streetlight_flag', 'traffic_signal_flag', 'garbage_flag', 'tree_hazard_flag']

--- Relationship Columns ---
['pair_id', 'complaint_a', 'complaint_b', 'complaint_a_text', 'complaint_b_text', 'issue_id_a', 'issue_id_b', 'category_a', 'category_b', 'distance_km', 'time_difference_hours', 'same_location_name', 'category_overlap', 'kg_relation_type', 'kg_relation_exists', 'same_issue', 'relationship_label']

--- Complaint Sample ---

,complaint_id,issue_id,complaint_text,issue_types,latitude,longitude,location_name,timestamp,urgency,responsible_departments,is_clustered_issue,source_type,road_damage_flag,roadside_flooding_flag,water_leakage_flag,electric_pole_flag,streetlight_flag,traffic_signal_flag,garbage_flag,tree_hazard_flag
0,C00001,I0001,Local residents report that a municipal water ...,Water Leakage,18.734922,73.677131,Talegaon Market,2025-09-24 18:00:00,Low,Water Department,1,synthetic_project_dataset,0,0,1,0,0,0,0,0
1,C00002,I0001,A complaint has been received that a damaged w...,Water Leakage,18.735156,73.676731,Talegaon Market,2025-09-22 19:15:00,Medium,Water Department,1,synthetic_project_dataset,0,0,1,0,0,0,0,0
2,C00003,I0001,A field report states that a water pipeline is...,Water Leakage,18.734915,73.675962,Talegaon Market,2025-09-23 17:45:00,Medium,Water Department,1,synthetic_project_dataset,0,0,1,0,0,0,0,0
3,C00004,I0001,A citizen reports that a damaged water connect...,Water Leakage,18.735415,73.676454,Talegaon Market,2025-09-24 11:45:00,Medium,Water Department,1,synthetic_project_dataset,0,0,1,0,0,0,0,0
4,C00005,I0002,A citizen reports that the drain is not carryi...,Drainage|Road Damage,18.598538,73.798398,Pimple Saudagar,2025-01-11 01:15:00,High,Drainage Department|Road Department,1,synthetic_project_dataset,1,0,0,0,0,0,0,0

--- Relationship Sample ---

,pair_id,complaint_a,complaint_b,complaint_a_text,complaint_b_text,issue_id_a,issue_id_b,category_a,category_b,distance_km,time_difference_hours,same_location_name,category_overlap,kg_relation_type,kg_relation_exists,same_issue,relationship_label
0,P000001,C03999,C01517,A complaint has been received that the traffic...,Residents report that the roadside drain is bl...,I1000,I0380,Traffic Signal,Drainage|Garbage,5.9833,68.50,0,NONE,NONE,0,0,Independent
1,P000002,C04681,C00666,A resident reports that the traffic light is n...,Please note that a damaged electricity pole is...,I1171,I0167,Traffic Signal,Electric Pole|Streetlight,0.4401,4358.25,0,NONE,NONE,0,0,Independent
2,P000003,C01361,C01364,A citizen reports that the signal remains red ...,A resident reports that the signal remains red...,I0341,I0341,Traffic Signal,Traffic Signal,0.1673,78.50,1,Traffic Signal,NONE,0,1,Duplicate
3,P000004,C05265,C05267,Residents report that an electric pole is lean...,Please note that a damaged electricity pole is...,I1317,I1317,Electric Pole|Tree Hazard,Electric Pole|Tree Hazard,0.0806,27.25,1,Electric Pole|Tree Hazard,can_damage|reverse_can_damage,1,1,Duplicate
4,P000005,C00013,C00014,A complaint has been received that the traffic...,People nearby report that the traffic light at...,I0004,I0004,Traffic Signal,Traffic Signal,0.0363,60.75,1,Traffic Signal,NONE,0,1,Duplicate

In [ ]:
# @title 🏷️ Check Multi-Label Issue Distribution

import numpy as np
import pandas as pd

# Your actual CSV contains 8 flag columns.
# Drainage is represented inside the pipe-separated issue_types column.
existing_flag_columns = [
    "road_damage_flag",
    "roadside_flooding_flag",
    "water_leakage_flag",
    "electric_pole_flag",
    "streetlight_flag",
    "traffic_signal_flag",
    "garbage_flag",
    "tree_hazard_flag"
]

# Check that all expected columns exist
missing_existing = [
    col for col in existing_flag_columns
    if col not in complaints_df.columns
]

if missing_existing:
    raise ValueError(
        f"Expected flag columns are missing: {missing_existing}"
    )

# Create drainage_flag from issue_types
complaints_df["drainage_flag"] = (
    complaints_df["issue_types"]
    .fillna("")
    .astype(str)
    .str.split("|")
    .apply(lambda labels: int("Drainage" in [x.strip() for x in labels]))
)

# Now we have all 9 ML labels
issue_flag_columns = [
    "road_damage_flag",
    "roadside_flooding_flag",
    "water_leakage_flag",
    "electric_pole_flag",
    "streetlight_flag",
    "traffic_signal_flag",
    "garbage_flag",
    "tree_hazard_flag",
    "drainage_flag"
]

print("Number of issue labels:", len(issue_flag_columns))
print("✅ drainage_flag created from issue_types")

# Count positive examples
label_counts = (
    complaints_df[issue_flag_columns]
    .sum()
    .sort_values(ascending=False)
)

print("\n--- Positive examples per label ---")
display(label_counts.to_frame("positive_count"))

# Percentage
label_percentages = (
    complaints_df[issue_flag_columns]
    .mean()
    .mul(100)
    .round(2)
)

print("\n--- Percentage of complaints containing each label ---")
display(label_percentages.to_frame("percentage"))

# Show examples
print("\n--- Example complaint + labels ---")

for idx in range(min(10, len(complaints_df))):

    row = complaints_df.iloc[idx]

    active_labels = [
        col.replace("_flag", "")
        for col in issue_flag_columns
        if row[col] == 1
    ]

    print("\nComplaint:")
    print(row["complaint_text"])

    print("Labels:")
    print(active_labels)

Number of issue labels: 9
✅ drainage_flag created from issue_types

--- Positive examples per label ---

                        positive_count
road_damage_flag                  1524
roadside_flooding_flag            1324
electric_pole_flag                1132
drainage_flag                     1048
water_leakage_flag                1044
tree_hazard_flag                  1044
traffic_signal_flag                984
streetlight_flag                   928
garbage_flag                       756

--- Percentage of complaints containing each label ---

                        percentage
road_damage_flag             25.40
roadside_flooding_flag       22.07
water_leakage_flag           17.40
electric_pole_flag           18.87
streetlight_flag             15.47
traffic_signal_flag          16.40
garbage_flag                 12.60
tree_hazard_flag             17.40
drainage_flag                17.47

--- Example complaint + labels ---

Complaint:
Local residents report that a municipal water pipe appears to have burst near Talegaon Market. The problem is affecting nearby residents.
Labels:
['water_leakage']

Complaint:
A complaint has been received that a damaged water connection is causing leakage near Talegaon Market. The issue has remained unresolved.
Labels:
['water_leakage']

Complaint:
A field report states that a water pipeline is leaking near Talegaon Market. The issue has remained unresolved.
Labels:
['water_leakage']

Complaint:
A citizen reports that a damaged water connection is causing leakage near Talegaon Market. The problem is affecting nearby residents.
Labels:
['water_leakage']

Complaint:
A citizen reports that the drain is not carrying water properly, with a deep pothole has formed on the road near Pimple Saudagar. Residents are requesting coordinated action.
Labels:
['road_damage', 'drainage']

Complaint:
A citizen reports that a drain cover is damaged, with a large broken patch is making the road unsafe near Pimple Saudagar. Residents are requesting coordinated action.
Labels:
['road_damage', 'drainage']

Complaint:
Please note that the storm-water drain is overflowing while the road surface is badly damaged near Pimple Saudagar. Residents are requesting coordinated action.
Labels:
['road_damage', 'drainage']

Complaint:
A coordinated complaint states that a drainage line appears to be blocked, with multiple potholes are causing problems for vehicles near Pimple Saudagar. Residents are requesting coordinated action.
Labels:
['road_damage', 'drainage']

Complaint:
A citizen reports that the road is flooded near the side drain near Kiwale. The problem is affecting nearby residents.
Labels:
['roadside_flooding']

Complaint:
A complaint has been received that water is collecting on the roadside after rain near Kiwale. The issue has remained unresolved.
Labels:
['roadside_flooding']

In [ ]:
# @title 🧠 Load Pretrained MiniLM Model

!pip -q install -U sentence-transformers

from sentence_transformers import SentenceTransformer
import torch

# Select GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# Load pretrained embedding model
embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    device=device
)

print("\n✅ MiniLM model loaded successfully")
print(
    "Embedding dimension:",
    embedding_model.get_sentence_embedding_dimension()
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 740.6/740.6 kB 13.6 MB/s eta 0:00:00
Device: cuda
GPU: Tesla T4

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

✅ MiniLM model loaded successfully
Embedding dimension: 384

/tmp/ipykernel_713/1584246335.py:25: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  embedding_model.get_sentence_embedding_dimension()

In [ ]:
# @title 🚀 Verify GPU Before Embedding Generation

import torch

print("===== GrievanceIQ Training Progress =====")
print("Step: 4 / 12")
print("Completed: MiniLM model loaded")
print("Remaining after this: 8 major steps")

print("\n--- Hardware Check ---")

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("✅ GPU detected")
    print("GPU name:", torch.cuda.get_device_name(0))
    device = "cuda"
else:
    print("❌ GPU NOT detected")
    print("Please enable GPU from:")
    print("Runtime → Change runtime type → GPU")

print("\n--- MiniLM Check ---")
print("Embedding dimension:",
      embedding_model.get_embedding_dimension())

===== GrievanceIQ Training Progress =====
Step: 4 / 12
Completed: MiniLM model loaded
Remaining after this: 8 major steps

--- Hardware Check ---
PyTorch version: 2.11.0+cu128
CUDA available: True
✅ GPU detected
GPU name: Tesla T4

--- MiniLM Check ---
Embedding dimension: 384

In [ ]:
# @title 🧠 Step 5/12 — Reload Datasets + MiniLM on T4 GPU

import os
import pandas as pd
import torch
from sentence_transformers import SentenceTransformer

# ============================================================
# 1. GOOGLE DRIVE PATH
# ============================================================

DATA_DIR = "/content/drive/MyDrive/GrievanceIQ Dataset"

complaints_path = os.path.join(
    DATA_DIR,
    "grievanceiq_complaints_multilabel_6000.csv"
)

relationships_path = os.path.join(
    DATA_DIR,
    "grievanceiq_relationship_pairs_16000.csv"
)

# ============================================================
# 2. LOAD DATASETS
# ============================================================

complaints_df = pd.read_csv(complaints_path)
relationships_df = pd.read_csv(relationships_path)

print("===== GrievanceIQ Training Progress =====")
print("Step: 5 / 12")
print()

print("✅ Complaints loaded:", complaints_df.shape)
print("✅ Relationship pairs loaded:", relationships_df.shape)

# Expected:
# (6000, 20)
# (16000, 17)

# ============================================================
# 3. CREATE DRAINAGE FLAG
# ============================================================

complaints_df["drainage_flag"] = (
    complaints_df["issue_types"]
    .fillna("")
    .astype(str)
    .str.split("|")
    .apply(
        lambda labels: int(
            "Drainage" in [x.strip() for x in labels]
        )
    )
)

# ============================================================
# 4. DEFINE 9 TARGET LABELS
# ============================================================

issue_flag_columns = [
    "road_damage_flag",
    "roadside_flooding_flag",
    "water_leakage_flag",
    "electric_pole_flag",
    "streetlight_flag",
    "traffic_signal_flag",
    "garbage_flag",
    "tree_hazard_flag",
    "drainage_flag"
]

print("\n✅ Number of issue labels:", len(issue_flag_columns))

# ============================================================
# 5. CHECK GPU
# ============================================================

print("\n--- GPU ---")

if torch.cuda.is_available():
    device = "cuda"
    print("✅ GPU:", torch.cuda.get_device_name(0))
else:
    device = "cpu"
    print("⚠️ GPU unavailable, using CPU")

# ============================================================
# 6. LOAD PRETRAINED MINILM
# ============================================================

print("\n--- Loading MiniLM ---")
print("Model: sentence-transformers/all-MiniLM-L6-v2")

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    device=device
)

embedding_dimension = embedding_model.get_embedding_dimension()

print("\n✅ MiniLM loaded successfully")
print("Device:", device)
print("Embedding dimension:", embedding_dimension)

# ============================================================
# 7. FINAL VERIFICATION
# ============================================================

print("\n===== Verification =====")

print("Complaints:", len(complaints_df))
print("Relationship pairs:", len(relationships_df))
print("Issue labels:", len(issue_flag_columns))
print("Embedding dimension:", embedding_dimension)

if device == "cuda" and embedding_dimension == 384:
    print("\n🎉 STEP 5 COMPLETE")
    print("Ready for Step 6: Generate 6,000 complaint embeddings")
else:
    print("\n⚠️ Please check GPU/model configuration")

===== GrievanceIQ Training Progress =====
Step: 5 / 12

✅ Complaints loaded: (6000, 20)
✅ Relationship pairs loaded: (16000, 17)

✅ Number of issue labels: 9

--- GPU ---
✅ GPU: Tesla T4

--- Loading MiniLM ---
Model: sentence-transformers/all-MiniLM-L6-v2

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

✅ MiniLM loaded successfully
Device: cuda
Embedding dimension: 384

===== Verification =====
Complaints: 6000
Relationship pairs: 16000
Issue labels: 9
Embedding dimension: 384

🎉 STEP 5 COMPLETE
Ready for Step 6: Generate 6,000 complaint embeddings

In [ ]:
# @title 🔢 Step 6/12 — Generate 6,000 MiniLM Complaint Embeddings

import os
import time
import numpy as np
from tqdm.auto import tqdm

# ============================================================
# CONFIGURATION
# ============================================================

BATCH_SIZE = 64

embedding_save_path = os.path.join(
    DATA_DIR,
    "complaint_embeddings_6000.npy"
)

# ============================================================
# PREPARE TEXT
# ============================================================

complaint_texts = (
    complaints_df["complaint_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

TOTAL_COMPLAINTS = len(complaint_texts)

print("===== GrievanceIQ Training Progress =====")
print("Step: 6 / 12")
print("Task: Generate MiniLM embeddings")
print()
print("Total complaints:", TOTAL_COMPLAINTS)
print("Batch size:", BATCH_SIZE)
print()

# ============================================================
# CHECK WHETHER EMBEDDINGS ALREADY EXIST
# ============================================================

if os.path.exists(embedding_save_path):

    print("⚠️ Existing embedding file found:")
    print(embedding_save_path)

    existing_embeddings = np.load(embedding_save_path)

    print("Existing shape:", existing_embeddings.shape)

    if existing_embeddings.shape == (
        TOTAL_COMPLAINTS,
        embedding_model.get_embedding_dimension()
    ):
        print("\n✅ Existing embeddings are valid.")
        print("Skipping generation.")
        complaint_embeddings = existing_embeddings

    else:
        print("\n⚠️ Existing file has unexpected shape.")
        print("Regenerating embeddings...")
        os.remove(embedding_save_path)

# ============================================================
# GENERATE EMBEDDINGS IF NEEDED
# ============================================================

if "complaint_embeddings" not in locals():

    total_batches = (
        TOTAL_COMPLAINTS + BATCH_SIZE - 1
    ) // BATCH_SIZE

    print("Total batches:", total_batches)
    print()
    print("Starting embedding generation...\n")

    start_time = time.time()

    all_embeddings = []

    progress_bar = tqdm(
        range(0, TOTAL_COMPLAINTS, BATCH_SIZE),
        total=total_batches,
        desc="Embedding batches",
        unit="batch"
    )

    for batch_start in progress_bar:

        batch_end = min(
            batch_start + BATCH_SIZE,
            TOTAL_COMPLAINTS
        )

        batch_texts = complaint_texts[batch_start:batch_end]

        batch_embeddings = embedding_model.encode(
            batch_texts,
            batch_size=BATCH_SIZE,
            show_progress_bar=False,
            normalize_embeddings=True,
            convert_to_numpy=True
        )

        all_embeddings.append(batch_embeddings)

        completed = batch_end
        remaining = TOTAL_COMPLAINTS - completed

        elapsed = time.time() - start_time

        progress_bar.set_postfix(
            completed=f"{completed}/{TOTAL_COMPLAINTS}",
            remaining=remaining,
            elapsed=f"{elapsed/60:.1f} min"
        )

    # Combine all batches
    complaint_embeddings = np.vstack(all_embeddings)

    # ========================================================
    # SAVE
    # ========================================================

    np.save(
        embedding_save_path,
        complaint_embeddings
    )

    elapsed = time.time() - start_time

    print("\n✅ Embedding generation complete")
    print("Time taken:", round(elapsed / 60, 2), "minutes")

# ============================================================
# FINAL VERIFICATION
# ============================================================

print("\n===== STEP 6 VERIFICATION =====")

print("Embedding shape:", complaint_embeddings.shape)
print(
    "Expected shape:",
    (
        TOTAL_COMPLAINTS,
        embedding_model.get_embedding_dimension()
    )
)

print("Saved to:")
print(embedding_save_path)

# Check numeric values
print("\nFirst embedding:")
print(complaint_embeddings[0][:10])

print("\nData type:")
print(complaint_embeddings.dtype)

# Final checks
assert complaint_embeddings.shape == (
    TOTAL_COMPLAINTS,
    embedding_model.get_embedding_dimension()
)

assert np.isfinite(complaint_embeddings).all()

print("\n✅ Shape check passed")
print("✅ NaN/Inf check passed")
print("✅ 6,000 complaint embeddings ready")

print("\n🎉 STEP 6 COMPLETE")
print("Next: Step 7/12 — Grouped Train / Validation / Test Split")

===== GrievanceIQ Training Progress =====
Step: 6 / 12
Task: Generate MiniLM embeddings

Total complaints: 6000
Batch size: 64

⚠️ Existing embedding file found:
/content/drive/MyDrive/GrievanceIQ Dataset/complaint_embeddings_6000.npy
Existing shape: (6000, 384)

✅ Existing embeddings are valid.
Skipping generation.

===== STEP 6 VERIFICATION =====
Embedding shape: (6000, 384)
Expected shape: (6000, 384)
Saved to:
/content/drive/MyDrive/GrievanceIQ Dataset/complaint_embeddings_6000.npy

First embedding:
[ 0.07297087 -0.0373533   0.05323767 -0.06511207  0.00273478 -0.01167579
 -0.03094948  0.05172465 -0.05717056 -0.03773385]

Data type:
float32

✅ Shape check passed
✅ NaN/Inf check passed
✅ 6,000 complaint embeddings ready

🎉 STEP 6 COMPLETE
Next: Step 7/12 — Grouped Train / Validation / Test Split

In [ ]:
# @title ✂️ Step 7/12 — Grouped Train / Validation / Test Split

from sklearn.model_selection import GroupShuffleSplit
import numpy as np

print("===== GrievanceIQ Training Progress =====")
print("Step: 7 / 12")
print()

# ============================================================
# 1. PREPARE FEATURES AND TARGETS
# ============================================================

X = complaint_embeddings

Y = complaints_df[issue_flag_columns].astype(int).values

groups = complaints_df["issue_id"].astype(str).values

print("Total complaints:", len(X))
print("Embedding shape:", X.shape)
print("Target shape:", Y.shape)
print("Unique issue groups:", len(np.unique(groups)))

# ============================================================
# 2. FIRST SPLIT
#    85% train+validation
#    15% test
# ============================================================

gss_test = GroupShuffleSplit(
    n_splits=1,
    test_size=0.15,
    random_state=42
)

train_val_idx, test_idx = next(
    gss_test.split(
        X,
        Y,
        groups=groups
    )
)

# ============================================================
# 3. SECOND SPLIT
#    From the remaining 85%:
#    ~82.35% -> train
#    ~17.65% -> validation
#
# This gives approximately:
# train = 70% total
# val   = 15% total
# test  = 15% total
# ============================================================

train_val_groups = groups[train_val_idx]

gss_val = GroupShuffleSplit(
    n_splits=1,
    test_size=0.17647058823529413,
    random_state=42
)

train_rel_idx, val_rel_idx = next(
    gss_val.split(
        X[train_val_idx],
        Y[train_val_idx],
        groups=train_val_groups
    )
)

train_idx = train_val_idx[train_rel_idx]
val_idx = train_val_idx[val_rel_idx]

# ============================================================
# 4. DISPLAY COUNTS
# ============================================================

print("\n===== SPLIT COUNTS =====")

print("Total records:     ", len(X))
print("Training records:  ", len(train_idx))
print("Validation records:", len(val_idx))
print("Test records:      ", len(test_idx))

print("\n===== PERCENTAGES =====")

print(
    f"Training:   {len(train_idx)/len(X)*100:.2f}%"
)

print(
    f"Validation: {len(val_idx)/len(X)*100:.2f}%"
)

print(
    f"Test:       {len(test_idx)/len(X)*100:.2f}%"
)

# ============================================================
# 5. CHECK TOTAL
# ============================================================

total_after_split = (
    len(train_idx)
    + len(val_idx)
    + len(test_idx)
)

remaining = len(X) - total_after_split

print("\n===== RECORD ACCOUNTING =====")
print("Total original:", len(X))
print("Train + Validation + Test:", total_after_split)
print("Remaining:", remaining)

assert total_after_split == len(X)
assert remaining == 0

print("✅ All 6,000 records accounted for")

# ============================================================
# 6. CHECK FOR ISSUE_ID LEAKAGE
# ============================================================

train_groups = set(groups[train_idx])
val_groups = set(groups[val_idx])
test_groups = set(groups[test_idx])

train_val_overlap = train_groups.intersection(val_groups)
train_test_overlap = train_groups.intersection(test_groups)
val_test_overlap = val_groups.intersection(test_groups)

print("\n===== GROUP LEAKAGE CHECK =====")

print(
    "Train ↔ Validation overlapping issue_ids:",
    len(train_val_overlap)
)

print(
    "Train ↔ Test overlapping issue_ids:",
    len(train_test_overlap)
)

print(
    "Validation ↔ Test overlapping issue_ids:",
    len(val_test_overlap)
)

assert len(train_val_overlap) == 0
assert len(train_test_overlap) == 0
assert len(val_test_overlap) == 0

print("\n✅ No issue_id leakage detected")

# ============================================================
# 7. LABEL DISTRIBUTION
# ============================================================

print("\n===== LABEL DISTRIBUTION =====")

train_counts = complaints_df.iloc[train_idx][issue_flag_columns].sum()
val_counts = complaints_df.iloc[val_idx][issue_flag_columns].sum()
test_counts = complaints_df.iloc[test_idx][issue_flag_columns].sum()

distribution_df = np.column_stack([
    train_counts.values,
    val_counts.values,
    test_counts.values
])

import pandas as pd

distribution_table = pd.DataFrame(
    distribution_df,
    index=issue_flag_columns,
    columns=[
        "Train",
        "Validation",
        "Test"
    ]
)

display(distribution_table)

print("\n🎉 STEP 7 COMPLETE")
print("Next: Step 8/12 — Train the Multi-Label Classifier")

===== GrievanceIQ Training Progress =====
Step: 7 / 12

Total complaints: 6000
Embedding shape: (6000, 384)
Target shape: (6000, 9)
Unique issue groups: 1500

===== SPLIT COUNTS =====
Total records:      6000
Training records:   4196
Validation records: 904
Test records:       900

===== PERCENTAGES =====
Training:   69.93%
Validation: 15.07%
Test:       15.00%

===== RECORD ACCOUNTING =====
Total original: 6000
Train + Validation + Test: 6000
Remaining: 0
✅ All 6,000 records accounted for

===== GROUP LEAKAGE CHECK =====
Train ↔ Validation overlapping issue_ids: 0
Train ↔ Test overlapping issue_ids: 0
Validation ↔ Test overlapping issue_ids: 0

✅ No issue_id leakage detected

===== LABEL DISTRIBUTION =====

                        Train  Validation  Test
road_damage_flag         1100         180   244
roadside_flooding_flag    956         204   164
water_leakage_flag        716         168   160
electric_pole_flag        728         188   216
streetlight_flag          656         124   148
traffic_signal_flag       708         144   132
garbage_flag              480         152   124
tree_hazard_flag          736         132   176
drainage_flag             744         144   160

🎉 STEP 7 COMPLETE
Next: Step 8/12 — Train the Multi-Label Classifier

In [ ]:
# @title 🤖 Step 8/12 — Train Multi-Label Classifier

import os
import json
import time
import joblib
import numpy as np

from sklearn.linear_model import LogisticRegression

# ============================================================
# STEP INFORMATION
# ============================================================

print("===== GrievanceIQ Training Progress =====")
print("Step: 8 / 12")
print()

print("Training records:", len(train_idx))
print("Validation records:", len(val_idx))
print("Test records:", len(test_idx))
print("Number of labels:", len(issue_flag_columns))
print()

# ============================================================
# CHECK TRAINING DATA
# ============================================================

X_train = complaint_embeddings[train_idx]
Y_train = complaints_df.iloc[train_idx][issue_flag_columns].astype(int).values

print("Training embedding shape:", X_train.shape)
print("Training target shape:", Y_train.shape)

assert X_train.shape[0] == len(train_idx)
assert Y_train.shape[0] == len(train_idx)

# ============================================================
# CREATE MODEL DIRECTORY
# ============================================================

MODEL_DIR = os.path.join(
    DATA_DIR,
    "trained_models"
)

os.makedirs(MODEL_DIR, exist_ok=True)

CHECKPOINT_DIR = os.path.join(
    MODEL_DIR,
    "multilabel_checkpoints"
)

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

print("\nModel directory:")
print(MODEL_DIR)

# ============================================================
# TRAIN 9 BINARY MODELS
# ============================================================

trained_models = {}

training_times = {}

TOTAL_LABELS = len(issue_flag_columns)

print("\n========================================")
print("STARTING MULTI-LABEL TRAINING")
print("========================================\n")

overall_start = time.time()

for label_number, label in enumerate(issue_flag_columns, start=1):

    remaining_labels = TOTAL_LABELS - label_number

    print("----------------------------------------")
    print(f"Label {label_number}/{TOTAL_LABELS}")
    print(f"Current label: {label}")
    print(f"Completed labels: {label_number - 1}")
    print(f"Remaining labels: {remaining_labels}")
    print("----------------------------------------")

    # --------------------------------------------------------
    # Get binary target
    # --------------------------------------------------------

    y_label = Y_train[:, label_number - 1]

    positive_count = int(y_label.sum())
    negative_count = int(len(y_label) - positive_count)

    print("Positive examples:", positive_count)
    print("Negative examples:", negative_count)

    # --------------------------------------------------------
    # Train Logistic Regression
    # --------------------------------------------------------

    model = LogisticRegression(
        max_iter=3000,
        class_weight="balanced",
        solver="liblinear",
        random_state=42
    )

    start_time = time.time()

    model.fit(
        X_train,
        y_label
    )

    elapsed = time.time() - start_time

    trained_models[label] = model
    training_times[label] = elapsed

    # --------------------------------------------------------
    # Save checkpoint immediately
    # --------------------------------------------------------

    checkpoint_path = os.path.join(
        CHECKPOINT_DIR,
        f"{label}.joblib"
    )

    joblib.dump(
        model,
        checkpoint_path
    )

    print(f"✅ Model trained for: {label}")
    print(f"Training time: {elapsed:.2f} seconds")
    print("Checkpoint saved:")
    print(checkpoint_path)

    print(
        f"Progress: {label_number}/{TOTAL_LABELS} "
        f"labels complete"
    )

# ============================================================
# SAVE ALL MODELS TO ONE FILE
# ============================================================

all_models_path = os.path.join(
    MODEL_DIR,
    "multilabel_classifier.joblib"
)

joblib.dump(
    trained_models,
    all_models_path
)

# ============================================================
# SAVE LABEL ORDER
# ============================================================

labels_path = os.path.join(
    MODEL_DIR,
    "issue_labels.json"
)

with open(labels_path, "w") as f:
    json.dump(
        issue_flag_columns,
        f,
        indent=2
    )

# ============================================================
# SAVE TRAINING CONFIGURATION
# ============================================================

config = {
    "embedding_model": "sentence-transformers/all-MiniLM-L6-v2",
    "embedding_dimension": 384,
    "classifier": "LogisticRegression",
    "solver": "liblinear",
    "max_iter": 3000,
    "class_weight": "balanced",
    "random_state": 42,
    "number_of_labels": len(issue_flag_columns),
    "labels": issue_flag_columns,
    "training_records": len(train_idx),
    "validation_records": len(val_idx),
    "test_records": len(test_idx),
    "group_split": True,
    "group_column": "issue_id"
}

config_path = os.path.join(
    MODEL_DIR,
    "multilabel_training_config.json"
)

with open(config_path, "w") as f:
    json.dump(
        config,
        f,
        indent=2
    )

# ============================================================
# FINAL SUMMARY
# ============================================================

overall_elapsed = time.time() - overall_start

print("\n========================================")
print("🎉 STEP 8 COMPLETE")
print("========================================")

print("\nLabels trained:", len(trained_models))
print("Expected labels:", TOTAL_LABELS)

print("\nTraining records used:", len(train_idx))
print("Validation records NOT used for fitting:", len(val_idx))
print("Test records NOT used for fitting:", len(test_idx))

print("\nTotal training time:")
print(f"{overall_elapsed / 60:.2f} minutes")

print("\n===== TRAINING TIME PER LABEL =====")

for label, seconds in training_times.items():
    print(f"{label}: {seconds:.2f} sec")

print("\n===== SAVED FILES =====")

print("Main model:")
print(all_models_path)

print("\nLabels:")
print(labels_path)

print("\nConfiguration:")
print(config_path)

print("\nCheckpoints:")
print(CHECKPOINT_DIR)

print("\nRemaining major steps: 4")
print("Next: Step 9/12 — Validation + threshold tuning + final test evaluation")

===== GrievanceIQ Training Progress =====
Step: 8 / 12

Training records: 4196
Validation records: 904
Test records: 900
Number of labels: 9

Training embedding shape: (4196, 384)
Training target shape: (4196, 9)

Model directory:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models

========================================
STARTING MULTI-LABEL TRAINING
========================================

----------------------------------------
Label 1/9
Current label: road_damage_flag
Completed labels: 0
Remaining labels: 8
----------------------------------------
Positive examples: 1100
Negative examples: 3096
✅ Model trained for: road_damage_flag
Training time: 0.24 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/road_damage_flag.joblib
Progress: 1/9 labels complete
----------------------------------------
Label 2/9
Current label: roadside_flooding_flag
Completed labels: 1
Remaining labels: 7
----------------------------------------
Positive examples: 956
Negative examples: 3240
✅ Model trained for: roadside_flooding_flag
Training time: 0.74 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/roadside_flooding_flag.joblib
Progress: 2/9 labels complete
----------------------------------------
Label 3/9
Current label: water_leakage_flag
Completed labels: 2
Remaining labels: 6
----------------------------------------
Positive examples: 716
Negative examples: 3480
✅ Model trained for: water_leakage_flag
Training time: 1.01 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/water_leakage_flag.joblib
Progress: 3/9 labels complete
----------------------------------------
Label 4/9
Current label: electric_pole_flag
Completed labels: 3
Remaining labels: 5
----------------------------------------
Positive examples: 728
Negative examples: 3468
✅ Model trained for: electric_pole_flag
Training time: 0.48 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/electric_pole_flag.joblib
Progress: 4/9 labels complete
----------------------------------------
Label 5/9
Current label: streetlight_flag
Completed labels: 4
Remaining labels: 4
----------------------------------------
Positive examples: 656
Negative examples: 3540
✅ Model trained for: streetlight_flag
Training time: 0.79 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/streetlight_flag.joblib
Progress: 5/9 labels complete
----------------------------------------
Label 6/9
Current label: traffic_signal_flag
Completed labels: 5
Remaining labels: 3
----------------------------------------
Positive examples: 708
Negative examples: 3488
✅ Model trained for: traffic_signal_flag
Training time: 0.69 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/traffic_signal_flag.joblib
Progress: 6/9 labels complete
----------------------------------------
Label 7/9
Current label: garbage_flag
Completed labels: 6
Remaining labels: 2
----------------------------------------
Positive examples: 480
Negative examples: 3716
✅ Model trained for: garbage_flag
Training time: 0.41 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/garbage_flag.joblib
Progress: 7/9 labels complete
----------------------------------------
Label 8/9
Current label: tree_hazard_flag
Completed labels: 7
Remaining labels: 1
----------------------------------------
Positive examples: 736
Negative examples: 3460
✅ Model trained for: tree_hazard_flag
Training time: 0.30 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/tree_hazard_flag.joblib
Progress: 8/9 labels complete
----------------------------------------
Label 9/9
Current label: drainage_flag
Completed labels: 8
Remaining labels: 0
----------------------------------------
Positive examples: 744
Negative examples: 3452
✅ Model trained for: drainage_flag
Training time: 0.27 seconds
Checkpoint saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints/drainage_flag.joblib
Progress: 9/9 labels complete

========================================
🎉 STEP 8 COMPLETE
========================================

Labels trained: 9
Expected labels: 9

Training records used: 4196
Validation records NOT used for fitting: 904
Test records NOT used for fitting: 900

Total training time:
0.17 minutes

===== TRAINING TIME PER LABEL =====
road_damage_flag: 0.24 sec
roadside_flooding_flag: 0.74 sec
water_leakage_flag: 1.01 sec
electric_pole_flag: 0.48 sec
streetlight_flag: 0.79 sec
traffic_signal_flag: 0.69 sec
garbage_flag: 0.41 sec
tree_hazard_flag: 0.30 sec
drainage_flag: 0.27 sec

===== SAVED FILES =====
Main model:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_classifier.joblib

Labels:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/issue_labels.json

Configuration:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_training_config.json

Checkpoints:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_checkpoints

Remaining major steps: 4
Next: Step 9/12 — Validation + threshold tuning + final test evaluation

In [ ]:
# @title 📊 Step 9/12 — Validation + Threshold Tuning + Final Test Evaluation

import os
import json
import numpy as np
import pandas as pd

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    hamming_loss,
    accuracy_score,
    classification_report,
    multilabel_confusion_matrix
)

# ============================================================
# STEP INFORMATION
# ============================================================

print("===== GrievanceIQ Training Progress =====")
print("Step: 9 / 12")
print()

print("Training records:   ", len(train_idx))
print("Validation records: ", len(val_idx))
print("Test records:       ", len(test_idx))
print("Labels:              ", len(issue_flag_columns))

print("\nIMPORTANT:")
print("Training set = already used for fitting")
print("Validation set = used now for threshold tuning")
print("Test set = kept untouched until final evaluation")

# ============================================================
# MAKE SURE TRAINED MODELS EXIST
# ============================================================

if "trained_models" not in locals():

    print("\n⚠️ trained_models not found in memory.")
    print("Loading saved model from Google Drive...")

    all_models_path = os.path.join(
        DATA_DIR,
        "trained_models",
        "multilabel_classifier.joblib"
    )

    trained_models = joblib.load(all_models_path)

    print("✅ Saved model loaded")

# ============================================================
# PREPARE VALIDATION / TEST DATA
# ============================================================

X_val = complaint_embeddings[val_idx]
Y_val = complaints_df.iloc[val_idx][issue_flag_columns].astype(int).values

X_test = complaint_embeddings[test_idx]
Y_test = complaints_df.iloc[test_idx][issue_flag_columns].astype(int).values

print("\nValidation shape:")
print("X_val:", X_val.shape)
print("Y_val:", Y_val.shape)

print("\nTest shape:")
print("X_test:", X_test.shape)
print("Y_test:", Y_test.shape)

# ============================================================
# GET VALIDATION PROBABILITIES
# ============================================================

print("\n========================================")
print("GENERATING VALIDATION PROBABILITIES")
print("========================================")

val_probabilities = np.zeros(
    (len(val_idx), len(issue_flag_columns)),
    dtype=np.float32
)

for label_number, label in enumerate(issue_flag_columns, start=1):

    model = trained_models[label]

    val_probabilities[:, label_number - 1] = (
        model.predict_proba(X_val)[:, 1]
    )

    remaining = len(issue_flag_columns) - label_number

    print(
        f"Validation probability: "
        f"{label_number}/{len(issue_flag_columns)} | "
        f"Completed={label_number} | "
        f"Remaining={remaining}"
    )

print("\n✅ Validation probabilities generated")

# ============================================================
# THRESHOLD TUNING
# ============================================================

print("\n========================================")
print("TUNING LABEL THRESHOLDS")
print("========================================")

thresholds = {}

threshold_values = np.arange(
    0.10,
    0.91,
    0.01
)

threshold_results = []

for label_number, label in enumerate(issue_flag_columns):

    y_true = Y_val[:, label_number]
    probabilities = val_probabilities[:, label_number]

    best_threshold = 0.50
    best_f1 = -1.0

    for threshold in threshold_values:

        y_pred = (
            probabilities >= threshold
        ).astype(int)

        score = f1_score(
            y_true,
            y_pred,
            zero_division=0
        )

        if score > best_f1:

            best_f1 = score
            best_threshold = float(threshold)

    thresholds[label] = best_threshold

    threshold_results.append({
        "label": label,
        "best_threshold": best_threshold,
        "validation_f1": best_f1
    })

    print(
        f"{label}: "
        f"threshold={best_threshold:.2f}, "
        f"validation F1={best_f1:.4f}"
    )

threshold_df = pd.DataFrame(threshold_results)

print("\n✅ Threshold tuning complete")

display(threshold_df)

# ============================================================
# VALIDATION PREDICTIONS USING TUNED THRESHOLDS
# ============================================================

val_pred = np.zeros_like(
    Y_val,
    dtype=int
)

for label_number, label in enumerate(issue_flag_columns):

    val_pred[:, label_number] = (
        val_probabilities[:, label_number]
        >= thresholds[label]
    ).astype(int)

# ============================================================
# VALIDATION METRICS
# ============================================================

val_micro_precision = precision_score(
    Y_val,
    val_pred,
    average="micro",
    zero_division=0
)

val_micro_recall = recall_score(
    Y_val,
    val_pred,
    average="micro",
    zero_division=0
)

val_micro_f1 = f1_score(
    Y_val,
    val_pred,
    average="micro",
    zero_division=0
)

val_macro_f1 = f1_score(
    Y_val,
    val_pred,
    average="macro",
    zero_division=0
)

val_hamming = hamming_loss(
    Y_val,
    val_pred
)

val_exact_match = accuracy_score(
    Y_val,
    val_pred
)

print("\n========================================")
print("VALIDATION RESULTS")
print("========================================")

print(f"Micro Precision : {val_micro_precision:.4f}")
print(f"Micro Recall    : {val_micro_recall:.4f}")
print(f"Micro F1        : {val_micro_f1:.4f}")
print(f"Macro F1        : {val_macro_f1:.4f}")
print(f"Hamming Loss    : {val_hamming:.4f}")
print(f"Exact Match     : {val_exact_match:.4f}")

# ============================================================
# FINAL TEST PROBABILITIES
# ============================================================

print("\n========================================")
print("GENERATING FINAL TEST PREDICTIONS")
print("========================================")

test_probabilities = np.zeros(
    (len(test_idx), len(issue_flag_columns)),
    dtype=np.float32
)

for label_number, label in enumerate(issue_flag_columns, start=1):

    model = trained_models[label]

    test_probabilities[:, label_number - 1] = (
        model.predict_proba(X_test)[:, 1]
    )

    remaining = len(issue_flag_columns) - label_number

    print(
        f"Test prediction: "
        f"{label_number}/{len(issue_flag_columns)} | "
        f"Completed={label_number} | "
        f"Remaining={remaining}"
    )

# ============================================================
# APPLY VALIDATION-TUNED THRESHOLDS TO TEST
# ============================================================

test_pred = np.zeros_like(
    Y_test,
    dtype=int
)

for label_number, label in enumerate(issue_flag_columns):

    test_pred[:, label_number] = (
        test_probabilities[:, label_number]
        >= thresholds[label]
    ).astype(int)

# ============================================================
# FINAL TEST METRICS
# ============================================================

test_micro_precision = precision_score(
    Y_test,
    test_pred,
    average="micro",
    zero_division=0
)

test_micro_recall = recall_score(
    Y_test,
    test_pred,
    average="micro",
    zero_division=0
)

test_micro_f1 = f1_score(
    Y_test,
    test_pred,
    average="micro",
    zero_division=0
)

test_macro_precision = precision_score(
    Y_test,
    test_pred,
    average="macro",
    zero_division=0
)

test_macro_recall = recall_score(
    Y_test,
    test_pred,
    average="macro",
    zero_division=0
)

test_macro_f1 = f1_score(
    Y_test,
    test_pred,
    average="macro",
    zero_division=0
)

test_hamming = hamming_loss(
    Y_test,
    test_pred
)

test_exact_match = accuracy_score(
    Y_test,
    test_pred
)

print("\n========================================")
print("🎯 FINAL TEST RESULTS")
print("========================================")

print(f"Micro Precision : {test_micro_precision:.4f}")
print(f"Micro Recall    : {test_micro_recall:.4f}")
print(f"Micro F1        : {test_micro_f1:.4f}")
print(f"Macro Precision : {test_macro_precision:.4f}")
print(f"Macro Recall    : {test_macro_recall:.4f}")
print(f"Macro F1        : {test_macro_f1:.4f}")
print(f"Hamming Loss    : {test_hamming:.4f}")
print(f"Exact Match     : {test_exact_match:.4f}")

# ============================================================
# PER-LABEL CLASSIFICATION REPORT
# ============================================================

print("\n========================================")
print("PER-LABEL TEST REPORT")
print("========================================")

report_dict = classification_report(
    Y_test,
    test_pred,
    target_names=issue_flag_columns,
    output_dict=True,
    zero_division=0
)

report_df = pd.DataFrame(report_dict).transpose()

display(
    report_df.round(4)
)

# ============================================================
# MULTI-LABEL CONFUSION MATRICES
# ============================================================

print("\n========================================")
print("CONFUSION MATRICES")
print("========================================")

confusion_matrices = multilabel_confusion_matrix(
    Y_test,
    test_pred
)

for i, label in enumerate(issue_flag_columns):

    cm = confusion_matrices[i]

    print(f"\n--- {label} ---")

    cm_df = pd.DataFrame(
        cm,
        index=[
            "Actual 0",
            "Actual 1"
        ],
        columns=[
            "Predicted 0",
            "Predicted 1"
        ]
    )

    display(cm_df)

# ============================================================
# SAVE METRICS
# ============================================================

MODEL_DIR = os.path.join(
    DATA_DIR,
    "trained_models"
)

metrics = {
    "training_records": int(len(train_idx)),
    "validation_records": int(len(val_idx)),
    "test_records": int(len(test_idx)),

    "embedding_model":
        "sentence-transformers/all-MiniLM-L6-v2",

    "embedding_dimension": 384,

    "validation": {
        "micro_precision": float(val_micro_precision),
        "micro_recall": float(val_micro_recall),
        "micro_f1": float(val_micro_f1),
        "macro_f1": float(val_macro_f1),
        "hamming_loss": float(val_hamming),
        "exact_match": float(val_exact_match)
    },

    "test": {
        "micro_precision": float(test_micro_precision),
        "micro_recall": float(test_micro_recall),
        "micro_f1": float(test_micro_f1),
        "macro_precision": float(test_macro_precision),
        "macro_recall": float(test_macro_recall),
        "macro_f1": float(test_macro_f1),
        "hamming_loss": float(test_hamming),
        "exact_match": float(test_exact_match)
    },

    "thresholds": thresholds
}

metrics_path = os.path.join(
    MODEL_DIR,
    "multilabel_evaluation_metrics.json"
)

with open(metrics_path, "w") as f:
    json.dump(
        metrics,
        f,
        indent=2
    )

# Save threshold table
threshold_path = os.path.join(
    MODEL_DIR,
    "multilabel_thresholds.csv"
)

threshold_df.to_csv(
    threshold_path,
    index=False
)

# Save classification report
report_path = os.path.join(
    MODEL_DIR,
    "multilabel_classification_report.csv"
)

report_df.to_csv(
    report_path
)

# Save test predictions
test_predictions_df = complaints_df.iloc[
    test_idx
][[
    "complaint_id",
    "issue_id",
    "complaint_text"
]].copy()

for i, label in enumerate(issue_flag_columns):

    test_predictions_df[
        f"actual_{label}"
    ] = Y_test[:, i]

    test_predictions_df[
        f"predicted_{label}"
    ] = test_pred[:, i]

    test_predictions_df[
        f"probability_{label}"
    ] = test_probabilities[:, i]

test_predictions_path = os.path.join(
    MODEL_DIR,
    "multilabel_test_predictions.csv"
)

test_predictions_df.to_csv(
    test_predictions_path,
    index=False
)

# ============================================================
# FINAL VERIFICATION
# ============================================================

print("\n========================================")
print("🎉 STEP 9 COMPLETE")
print("========================================")

print("Test records evaluated:", len(test_idx))
print("Remaining test records:", 0)

print("\nSaved evaluation files:")

print("\n1. Metrics:")
print(metrics_path)

print("\n2. Thresholds:")
print(threshold_path)

print("\n3. Classification report:")
print(report_path)

print("\n4. Test predictions:")
print(test_predictions_path)

print("\n✅ Final test evaluation completed")
print("✅ Test set was evaluated after threshold tuning")
print("✅ Results saved to Google Drive")

print("\nNext: Step 10/12 — Prepare the 16,000 relationship-pair dataset")

===== GrievanceIQ Training Progress =====
Step: 9 / 12

Training records:    4196
Validation records:  904
Test records:        900
Labels:               9

IMPORTANT:
Training set = already used for fitting
Validation set = used now for threshold tuning
Test set = kept untouched until final evaluation

Validation shape:
X_val: (904, 384)
Y_val: (904, 9)

Test shape:
X_test: (900, 384)
Y_test: (900, 9)

========================================
GENERATING VALIDATION PROBABILITIES
========================================
Validation probability: 1/9 | Completed=1 | Remaining=8
Validation probability: 2/9 | Completed=2 | Remaining=7
Validation probability: 3/9 | Completed=3 | Remaining=6
Validation probability: 4/9 | Completed=4 | Remaining=5
Validation probability: 5/9 | Completed=5 | Remaining=4
Validation probability: 6/9 | Completed=6 | Remaining=3
Validation probability: 7/9 | Completed=7 | Remaining=2
Validation probability: 8/9 | Completed=8 | Remaining=1
Validation probability: 9/9 | Completed=9 | Remaining=0

✅ Validation probabilities generated

========================================
TUNING LABEL THRESHOLDS
========================================
road_damage_flag: threshold=0.59, validation F1=1.0000
roadside_flooding_flag: threshold=0.61, validation F1=0.9730
water_leakage_flag: threshold=0.51, validation F1=0.9911
electric_pole_flag: threshold=0.58, validation F1=1.0000
streetlight_flag: threshold=0.58, validation F1=1.0000
traffic_signal_flag: threshold=0.60, validation F1=0.9965
garbage_flag: threshold=0.65, validation F1=0.9803
tree_hazard_flag: threshold=0.43, validation F1=1.0000
drainage_flag: threshold=0.66, validation F1=0.9965

✅ Threshold tuning complete

                    label  best_threshold  validation_f1
0        road_damage_flag            0.59       1.000000
1  roadside_flooding_flag            0.61       0.972973
2      water_leakage_flag            0.51       0.991098
3      electric_pole_flag            0.58       1.000000
4        streetlight_flag            0.58       1.000000
5     traffic_signal_flag            0.60       0.996516
6            garbage_flag            0.65       0.980263
7        tree_hazard_flag            0.43       1.000000
8           drainage_flag            0.66       0.996540

========================================
VALIDATION RESULTS
========================================
Micro Precision : 0.9923
Micro Recall    : 0.9923
Micro F1        : 0.9923
Macro F1        : 0.9930
Hamming Loss    : 0.0027
Exact Match     : 0.9757

========================================
GENERATING FINAL TEST PREDICTIONS
========================================
Test prediction: 1/9 | Completed=1 | Remaining=8
Test prediction: 2/9 | Completed=2 | Remaining=7
Test prediction: 3/9 | Completed=3 | Remaining=6
Test prediction: 4/9 | Completed=4 | Remaining=5
Test prediction: 5/9 | Completed=5 | Remaining=4
Test prediction: 6/9 | Completed=6 | Remaining=3
Test prediction: 7/9 | Completed=7 | Remaining=2
Test prediction: 8/9 | Completed=8 | Remaining=1
Test prediction: 9/9 | Completed=9 | Remaining=0

========================================
🎯 FINAL TEST RESULTS
========================================
Micro Precision : 0.9786
Micro Recall    : 0.9921
Micro F1        : 0.9853
Macro Precision : 0.9783
Macro Recall    : 0.9920
Macro F1        : 0.9850
Hamming Loss    : 0.0056
Exact Match     : 0.9500

========================================
PER-LABEL TEST REPORT
========================================

                        precision  recall  f1-score  support
road_damage_flag           0.9959  0.9918    0.9938    244.0
roadside_flooding_flag     0.8864  0.9512    0.9176    164.0
water_leakage_flag         0.9938  1.0000    0.9969    160.0
electric_pole_flag         0.9954  1.0000    0.9977    216.0
streetlight_flag           0.9933  1.0000    0.9966    148.0
traffic_signal_flag        0.9774  0.9848    0.9811    132.0
garbage_flag               0.9920  1.0000    0.9960    124.0
tree_hazard_flag           0.9888  1.0000    0.9944    176.0
drainage_flag              0.9816  1.0000    0.9907    160.0
micro avg                  0.9786  0.9921    0.9853   1524.0
macro avg                  0.9783  0.9920    0.9850   1524.0
weighted avg               0.9793  0.9921    0.9856   1524.0
samples avg                0.9867  0.9946    0.9884   1524.0

========================================
CONFUSION MATRICES
========================================

--- road_damage_flag ---

          Predicted 0  Predicted 1
Actual 0          655            1
Actual 1            2          242

--- roadside_flooding_flag ---

          Predicted 0  Predicted 1
Actual 0          716           20
Actual 1            8          156

--- water_leakage_flag ---

          Predicted 0  Predicted 1
Actual 0          739            1
Actual 1            0          160

--- electric_pole_flag ---

          Predicted 0  Predicted 1
Actual 0          683            1
Actual 1            0          216

--- streetlight_flag ---

          Predicted 0  Predicted 1
Actual 0          751            1
Actual 1            0          148

--- traffic_signal_flag ---

          Predicted 0  Predicted 1
Actual 0          765            3
Actual 1            2          130

--- garbage_flag ---

          Predicted 0  Predicted 1
Actual 0          775            1
Actual 1            0          124

--- tree_hazard_flag ---

          Predicted 0  Predicted 1
Actual 0          722            2
Actual 1            0          176

--- drainage_flag ---

          Predicted 0  Predicted 1
Actual 0          737            3
Actual 1            0          160

========================================
🎉 STEP 9 COMPLETE
========================================
Test records evaluated: 900
Remaining test records: 0

Saved evaluation files:

1. Metrics:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_evaluation_metrics.json

2. Thresholds:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_thresholds.csv

3. Classification report:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_classification_report.csv

4. Test predictions:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/multilabel_test_predictions.csv

✅ Final test evaluation completed
✅ Test set was evaluated after threshold tuning
✅ Results saved to Google Drive

Next: Step 10/12 — Prepare the 16,000 relationship-pair dataset

In [ ]:
# @title 🔍 Step 10/12A — Inspect Relationship Dataset

import pandas as pd
import numpy as np
import os

print("===== GrievanceIQ Training Progress =====")
print("Step: 10 / 12")
print("Part A: Relationship dataset verification")
print()

print("Total relationship pairs:", len(relationships_df))

# ------------------------------------------------------------
# LABEL DISTRIBUTION
# ------------------------------------------------------------

label_counts = (
    relationships_df["relationship_label"]
    .value_counts()
    .reindex([
        "Duplicate",
        "Similar",
        "Related",
        "Independent"
    ])
)

print("\n===== RELATIONSHIP LABEL COUNTS =====")
display(label_counts.to_frame("count"))

print("\n===== RELATIONSHIP PERCENTAGES =====")

label_percentages = (
    relationships_df["relationship_label"]
    .value_counts(normalize=True)
    .reindex([
        "Duplicate",
        "Similar",
        "Related",
        "Independent"
    ])
    .mul(100)
    .round(2)
)

display(label_percentages.to_frame("percentage"))

# ------------------------------------------------------------
# TOTAL ACCOUNTING
# ------------------------------------------------------------

count_total = int(label_counts.sum())

print("\n===== RECORD ACCOUNTING =====")
print("Total input pairs:", len(relationships_df))
print("Pairs counted:", count_total)
print("Remaining:", len(relationships_df) - count_total)

assert count_total == len(relationships_df)

print("✅ All relationship pairs accounted for")

# ------------------------------------------------------------
# MISSING VALUES
# ------------------------------------------------------------

print("\n===== MISSING VALUE CHECK =====")

missing_values = (
    relationships_df.isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    missing_values[missing_values > 0]
    .to_frame("missing_count")
)

# ------------------------------------------------------------
# CHECK REQUIRED TEXT
# ------------------------------------------------------------

empty_a = (
    relationships_df["complaint_a_text"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

empty_b = (
    relationships_df["complaint_b_text"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

print("\nEmpty Complaint A texts:", empty_a)
print("Empty Complaint B texts:", empty_b)

assert empty_a == 0
assert empty_b == 0

print("\n✅ Complaint texts are available")

# ------------------------------------------------------------
# SHOW SAMPLE FROM EACH CLASS
# ------------------------------------------------------------

print("\n===== ONE SAMPLE PER RELATIONSHIP =====")

for label in [
    "Duplicate",
    "Similar",
    "Related",
    "Independent"
]:

    sample = relationships_df[
        relationships_df["relationship_label"] == label
    ].iloc[0]

    print("\n----------------------------------------")
    print("Label:", label)
    print("Complaint A:", sample["complaint_a_text"])
    print("Complaint B:", sample["complaint_b_text"])
    print("Distance km:", sample["distance_km"])
    print(
        "Time difference hours:",
        sample["time_difference_hours"]
    )
    print(
        "KG relation:",
        sample["kg_relation_type"]
    )

print("\n🎉 STEP 10A COMPLETE")
print("Relationship pairs verified:", len(relationships_df))
print("Remaining after verification: 0")
print("Next: Step 10B — Generate pair semantic similarities")

===== GrievanceIQ Training Progress =====
Step: 10 / 12
Part A: Relationship dataset verification

Total relationship pairs: 16000

===== RELATIONSHIP LABEL COUNTS =====

                    count
relationship_label
Duplicate            4000
Similar              3500
Related              3500
Independent          5000

===== RELATIONSHIP PERCENTAGES =====

                    percentage
relationship_label
Duplicate                25.00
Similar                  21.88
Related                  21.88
Independent              31.25

===== RECORD ACCOUNTING =====
Total input pairs: 16000
Pairs counted: 16000
Remaining: 0
✅ All relationship pairs accounted for

===== MISSING VALUE CHECK =====

Empty DataFrame
Columns: [missing_count]
Index: []

Empty Complaint A texts: 0
Empty Complaint B texts: 0

✅ Complaint texts are available

===== ONE SAMPLE PER RELATIONSHIP =====

----------------------------------------
Label: Duplicate
Complaint A: A citizen reports that the signal remains red for too long near PCCOE Main Road. The problem is affecting nearby residents.
Complaint B: A resident reports that the signal remains red for too long near PCCOE Main Road. The issue has remained unresolved.
Distance km: 0.1673
Time difference hours: 78.5
KG relation: NONE

----------------------------------------
Label: Similar
Complaint A: A citizen reports that a damaged water connection is causing leakage near Talegaon Market. The problem is affecting nearby residents.
Complaint B: Please check whether the water supply line is leaking at the roadside near Pimpri Market. The issue has remained unresolved.
Distance km: 17.9594
Time difference hours: 4602.75
KG relation: NONE

----------------------------------------
Label: Related
Complaint A: A citizen reports that a large broken patch is making the road unsafe near Akurdi Market. Please arrange an inspection.
Complaint B: A complaint has been received that the traffic signal is malfunctioning near Akurdi Market. The problem is affecting nearby residents.
Distance km: 0.0964
Time difference hours: 7453.0
KG relation: reverse_can_affect

----------------------------------------
Label: Independent
Complaint A: A complaint has been received that the traffic light at the junction needs repair near Wakad Main Road. Residents are requesting action.
Complaint B: Residents report that the roadside drain is blocked while the roadside bin is overflowing near Nigdi Bus Stand. Residents are requesting coordinated action.
Distance km: 5.9833
Time difference hours: 68.5
KG relation: NONE

🎉 STEP 10A COMPLETE
Relationship pairs verified: 16000
Remaining after verification: 0
Next: Step 10B — Generate pair semantic similarities

In [ ]:
# @title 🧠 Step 10/12B — Compute Semantic Similarity for 16,000 Pairs

import numpy as np
import pandas as pd
import time
from tqdm.auto import tqdm

print("===== GrievanceIQ Training Progress =====")
print("Step: 10 / 12")
print("Part B: Semantic similarity generation")
print()

TOTAL_PAIRS = len(relationships_df)

print("Total relationship pairs:", TOTAL_PAIRS)
print("Embedding model:", "all-MiniLM-L6-v2")
print("Embedding dimension:",
      embedding_model.get_embedding_dimension())

# ============================================================
# TEXTS
# ============================================================

texts_a = (
    relationships_df["complaint_a_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

texts_b = (
    relationships_df["complaint_b_text"]
    .fillna("")
    .astype(str)
    .tolist()
)

# ============================================================
# ENCODE COMPLAINT A
# ============================================================

print("\n========================================")
print("Encoding Complaint A")
print("========================================")

start_a = time.time()

embeddings_a = embedding_model.encode(
    texts_a,
    batch_size=128,
    show_progress_bar=True,
    normalize_embeddings=True,
    convert_to_numpy=True
)

time_a = time.time() - start_a

print("\n✅ Complaint A embeddings complete")
print("Completed:", TOTAL_PAIRS)
print("Remaining:", 0)
print("Shape:", embeddings_a.shape)
print("Time:", round(time_a / 60, 2), "minutes")

# ============================================================
# ENCODE COMPLAINT B
# ============================================================

print("\n========================================")
print("Encoding Complaint B")
print("========================================")

start_b = time.time()

embeddings_b = embedding_model.encode(
    texts_b,
    batch_size=128,
    show_progress_bar=True,
    normalize_embeddings=True,
    convert_to_numpy=True
)

time_b = time.time() - start_b

print("\n✅ Complaint B embeddings complete")
print("Completed:", TOTAL_PAIRS)
print("Remaining:", 0)
print("Shape:", embeddings_b.shape)
print("Time:", round(time_b / 60, 2), "minutes")

# ============================================================
# COSINE SIMILARITY
# ============================================================
# Because the embeddings were normalized, cosine similarity
# is simply the row-wise dot product.

semantic_similarity = np.sum(
    embeddings_a * embeddings_b,
    axis=1
)

semantic_similarity = np.clip(
    semantic_similarity,
    -1.0,
    1.0
)

print("\n========================================")
print("SEMANTIC SIMILARITY")
print("========================================")

print("Completed pairs:", TOTAL_PAIRS)
print("Remaining pairs:", 0)

print(
    "Min similarity:",
    round(float(semantic_similarity.min()), 4)
)

print(
    "Max similarity:",
    round(float(semantic_similarity.max()), 4)
)

print(
    "Mean similarity:",
    round(float(semantic_similarity.mean()), 4)
)

print("\n✅ Semantic similarity calculated from raw texts")

# ============================================================
# ADD TO DATAFRAME
# ============================================================

relationships_prepared = relationships_df.copy()

relationships_prepared[
    "semantic_similarity"
] = semantic_similarity.astype(np.float32)

# ============================================================
# SAVE PREPARED DATASET
# ============================================================

prepared_path = os.path.join(
    DATA_DIR,
    "relationship_pairs_16000_prepared.csv"
)

relationships_prepared.to_csv(
    prepared_path,
    index=False
)

print("\n✅ Prepared dataset saved:")
print(prepared_path)

print("\nDataset shape:")
print(relationships_prepared.shape)

print("\n🎉 STEP 10B COMPLETE")
print("Completed pairs:", TOTAL_PAIRS)
print("Remaining pairs:", 0)
print("Next: Step 10C — Build leakage-safe relationship features")

===== GrievanceIQ Training Progress =====
Step: 10 / 12
Part B: Semantic similarity generation

Total relationship pairs: 16000
Embedding model: all-MiniLM-L6-v2
Embedding dimension: 384

========================================
Encoding Complaint A
========================================

Batches:   0%|          | 0/125 [00:00<?, ?it/s]

✅ Complaint A embeddings complete
Completed: 16000
Remaining: 0
Shape: (16000, 384)
Time: 0.18 minutes

========================================
Encoding Complaint B
========================================

Batches:   0%|          | 0/125 [00:00<?, ?it/s]

✅ Complaint B embeddings complete
Completed: 16000
Remaining: 0
Shape: (16000, 384)
Time: 0.19 minutes

========================================
SEMANTIC SIMILARITY
========================================
Completed pairs: 16000
Remaining pairs: 0
Min similarity: -0.0083
Max similarity: 0.9958
Mean similarity: 0.5134

✅ Semantic similarity calculated from raw texts

✅ Prepared dataset saved:
/content/drive/MyDrive/GrievanceIQ Dataset/relationship_pairs_16000_prepared.csv

Dataset shape:
(16000, 18)

🎉 STEP 10B COMPLETE
Completed pairs: 16000
Remaining pairs: 0
Next: Step 10C — Build leakage-safe relationship features

In [ ]:
# @title 🧩 Step 10C/12 — Corrected Leakage-Safe Relationship Features + Pair-Group Split

import os
import json
import numpy as np
import pandas as pd

from sklearn.model_selection import GroupShuffleSplit

print("===== GrievanceIQ Training Progress =====")
print("Step: 10 / 12")
print("Part C: Corrected relationship feature engineering")
print()

# ============================================================
# 1. LOAD PREPARED DATA
# ============================================================

prepared_path = os.path.join(
    DATA_DIR,
    "relationship_pairs_16000_prepared.csv"
)

relationships_prepared = pd.read_csv(
    prepared_path
)

print("Prepared dataset shape:", relationships_prepared.shape)

assert len(relationships_prepared) == 16000

# ============================================================
# 2. CHECK RELATIONSHIP CLASSES
# ============================================================

print("\n===== RELATIONSHIP CLASSES =====")

display(
    relationships_prepared["relationship_label"]
    .value_counts()
)

# ============================================================
# 3. CATEGORY MAPPING
# ============================================================

FINE_TO_COARSE = {
    "Road Damage": "Roads",
    "Roadside Flooding": "Roads",
    "Water Leakage": "Water Supply",
    "Electric Pole": "Electricity",
    "Drainage": "Drainage",
    "Garbage": "Waste Management",
    "Streetlight": "Public Infrastructure",
    "Traffic Signal": "Public Infrastructure",
    "Tree Hazard": "Public Infrastructure"
}

COARSE_CATEGORIES = [
    "Roads",
    "Water Supply",
    "Electricity",
    "Drainage",
    "Waste Management",
    "Public Infrastructure",
    "Other"
]

def parse_categories(value):

    if pd.isna(value):
        return []

    return [
        x.strip()
        for x in str(value).split("|")
        if x.strip()
    ]


def convert_to_coarse_categories(value):

    fine_categories = parse_categories(value)

    coarse_categories = []

    for category in fine_categories:

        mapped = FINE_TO_COARSE.get(
            category,
            "Other"
        )

        if mapped not in coarse_categories:
            coarse_categories.append(mapped)

    if not coarse_categories:
        coarse_categories = ["Other"]

    return coarse_categories


print("\nConverting fine-grained categories...")

relationships_prepared["coarse_categories_a"] = (
    relationships_prepared["category_a"]
    .apply(convert_to_coarse_categories)
)

relationships_prepared["coarse_categories_b"] = (
    relationships_prepared["category_b"]
    .apply(convert_to_coarse_categories)
)

relationships_prepared["coarse_category_a"] = (
    relationships_prepared["coarse_categories_a"]
    .apply(lambda x: x[0])
)

relationships_prepared["coarse_category_b"] = (
    relationships_prepared["coarse_categories_b"]
    .apply(lambda x: x[0])
)

relationships_prepared["same_category"] = (
    relationships_prepared["coarse_category_a"]
    ==
    relationships_prepared["coarse_category_b"]
).astype(int)

# ============================================================
# 4. LOCATION SCORE
# ============================================================

distance_km = pd.to_numeric(
    relationships_prepared["distance_km"],
    errors="coerce"
).fillna(999999)

relationships_prepared["location_score"] = (
    1.0
    -
    np.clip(
        distance_km / 0.5,
        0.0,
        1.0
    )
)

# ============================================================
# 5. TEMPORAL SCORE
# ============================================================

time_difference = pd.to_numeric(
    relationships_prepared["time_difference_hours"],
    errors="coerce"
).fillna(999999)

relationships_prepared["temporal_score"] = (
    1.0
    -
    np.clip(
        time_difference / 48.0,
        0.0,
        1.0
    )
)

# ============================================================
# 6. DUPLICATE SCORE
# ============================================================

relationships_prepared["duplicate_score"] = (
    0.50
    * relationships_prepared["semantic_similarity"]
    +
    0.30
    * relationships_prepared["location_score"]
    +
    0.20
    * relationships_prepared["temporal_score"]
)

relationships_prepared["duplicate_flag"] = (
    (
        relationships_prepared["duplicate_score"] >= 0.80
    )
    &
    (
        relationships_prepared["semantic_similarity"] >= 0.75
    )
).astype(int)

# ============================================================
# 7. BUILD EXACTLY 20 BACKEND-COMPATIBLE FEATURES
# ============================================================

feature_columns = [
    "semantic_similarity",
    "location_score",
    "temporal_score",
    "duplicate_score",
    "duplicate_flag",
    "same_category"
]

# 7 category A one-hot features
for category in COARSE_CATEGORIES:

    column = (
        "category_a_"
        + category.lower().replace(" ", "_")
    )

    relationships_prepared[column] = (
        relationships_prepared["coarse_category_a"]
        == category
    ).astype(int)

    feature_columns.append(column)

# 7 category B one-hot features
for category in COARSE_CATEGORIES:

    column = (
        "category_b_"
        + category.lower().replace(" ", "_")
    )

    relationships_prepared[column] = (
        relationships_prepared["coarse_category_b"]
        == category
    ).astype(int)

    feature_columns.append(column)

# ============================================================
# 8. VERIFY FEATURE COUNT
# ============================================================

print("\n===== FEATURE COUNT =====")

print("Feature count:", len(feature_columns))

assert len(feature_columns) == 20

print("✅ Exactly 20 features")

print("\nFeatures:")

for number, feature in enumerate(
    feature_columns,
    start=1
):
    print(
        f"{number:02d}. {feature}"
    )

# ============================================================
# 9. LEAKAGE CHECK
# ============================================================

print("\n===== LEAKAGE CHECK =====")

for forbidden in [
    "same_issue",
    "relationship_label"
]:

    if forbidden in feature_columns:
        raise ValueError(
            f"LEAKAGE DETECTED: {forbidden}"
        )

    print(
        f"{forbidden}: NOT USED ✅"
    )

if "category_overlap_binary" in feature_columns:

    raise ValueError(
        "category_overlap_binary should not be present"
    )

print(
    "category_overlap_binary: NOT USED ✅"
)

# ============================================================
# 10. CREATE X AND y
# ============================================================

X_relationship = (
    relationships_prepared[
        feature_columns
    ]
    .astype(np.float32)
    .values
)

y_relationship = (
    relationships_prepared[
        "relationship_label"
    ]
    .astype(str)
    .values
)

print("\n===== MATRIX SHAPES =====")

print(
    "X shape:",
    X_relationship.shape
)

print(
    "y shape:",
    y_relationship.shape
)

assert X_relationship.shape == (
    16000,
    20
)

assert y_relationship.shape == (
    16000,
)

print("✅ Feature matrix correct")

# ============================================================
# 11. NUMERIC CHECK
# ============================================================

print("\n===== NUMERIC CHECK =====")

nan_count = np.isnan(
    X_relationship
).sum()

inf_count = np.isinf(
    X_relationship
).sum()

print("NaN:", nan_count)
print("Infinite:", inf_count)

assert nan_count == 0
assert inf_count == 0

print("✅ No NaN")
print("✅ No infinite values")

# ============================================================
# 12. CANONICAL ISSUE-PAIR GROUP
# ============================================================
#
# Example:
# I0001 + I0042
# I0042 + I0001
#
# become the same group.
#
# This avoids exact pair-group leakage.
# ============================================================

print("\n========================================")
print("BUILDING CANONICAL ISSUE-PAIR GROUPS")
print("========================================")

issue_a = (
    relationships_prepared[
        "issue_id_a"
    ]
    .astype(str)
)

issue_b = (
    relationships_prepared[
        "issue_id_b"
    ]
    .astype(str)
)

relationships_prepared[
    "pair_group"
] = [
    "|".join(
        sorted([a, b])
    )
    for a, b in zip(
        issue_a,
        issue_b
    )
]

unique_pair_groups = (
    relationships_prepared[
        "pair_group"
    ]
    .nunique()
)

print(
    "Unique issue-pair groups:",
    unique_pair_groups
)

print(
    "Total relationship rows:",
    len(relationships_prepared)
)

# ============================================================
# 13. GROUPED TRAIN / VALIDATION / TEST SPLIT
# ============================================================

print("\n========================================")
print("PAIR-GROUP TRAIN / VALIDATION / TEST SPLIT")
print("========================================")

groups = (
    relationships_prepared[
        "pair_group"
    ]
    .astype(str)
    .values
)

# 85% train+validation
# 15% test

gss_test = GroupShuffleSplit(
    n_splits=1,
    test_size=0.15,
    random_state=42
)

train_val_idx, test_idx_rel = next(
    gss_test.split(
        X_relationship,
        y_relationship,
        groups=groups
    )
)

# From 85%:
# ~70% total train
# ~15% total validation

gss_val = GroupShuffleSplit(
    n_splits=1,
    test_size=0.17647058823529413,
    random_state=42
)

train_rel_idx, val_rel_idx = next(
    gss_val.split(
        X_relationship[train_val_idx],
        y_relationship[train_val_idx],
        groups=groups[train_val_idx]
    )
)

relationship_train_idx = (
    train_val_idx[
        train_rel_idx
    ]
)

relationship_val_idx = (
    train_val_idx[
        val_rel_idx
    ]
)

relationship_test_idx = (
    test_idx_rel
)

# ============================================================
# 14. COUNTS
# ============================================================

total_pairs = len(
    relationships_prepared
)

train_count = len(
    relationship_train_idx
)

val_count = len(
    relationship_val_idx
)

test_count = len(
    relationship_test_idx
)

accounted = (
    train_count
    +
    val_count
    +
    test_count
)

remaining = (
    total_pairs
    -
    accounted
)

print("\n===== RELATIONSHIP SPLIT COUNTS =====")

print(
    "Total pairs:      ",
    total_pairs
)

print(
    "Training pairs:   ",
    train_count
)

print(
    "Validation pairs: ",
    val_count
)

print(
    "Test pairs:       ",
    test_count
)

print(
    "Remaining pairs:  ",
    remaining
)

print("\n===== PERCENTAGES =====")

print(
    f"Training:   "
    f"{train_count / total_pairs * 100:.2f}%"
)

print(
    f"Validation: "
    f"{val_count / total_pairs * 100:.2f}%"
)

print(
    f"Test:       "
    f"{test_count / total_pairs * 100:.2f}%"
)

assert accounted == total_pairs
assert remaining == 0

print("\n✅ All 16,000 relationship pairs accounted for")

# ============================================================
# 15. CHECK PAIR-GROUP LEAKAGE
# ============================================================

train_groups = set(
    groups[
        relationship_train_idx
    ]
)

val_groups = set(
    groups[
        relationship_val_idx
    ]
)

test_groups = set(
    groups[
        relationship_test_idx
    ]
)

train_val_overlap = (
    train_groups
    &
    val_groups
)

train_test_overlap = (
    train_groups
    &
    test_groups
)

val_test_overlap = (
    val_groups
    &
    test_groups
)

print("\n===== PAIR-GROUP LEAKAGE CHECK =====")

print(
    "Train ↔ Validation:",
    len(train_val_overlap)
)

print(
    "Train ↔ Test:",
    len(train_test_overlap)
)

print(
    "Validation ↔ Test:",
    len(val_test_overlap)
)

assert len(train_val_overlap) == 0
assert len(train_test_overlap) == 0
assert len(val_test_overlap) == 0

print(
    "\n✅ No exact issue-pair group leakage"
)

# ============================================================
# 16. LABEL DISTRIBUTION
# ============================================================

print("\n===== LABEL DISTRIBUTION =====")

train_labels = (
    relationships_prepared
    .iloc[relationship_train_idx]
    ["relationship_label"]
    .value_counts()
)

val_labels = (
    relationships_prepared
    .iloc[relationship_val_idx]
    ["relationship_label"]
    .value_counts()
)

test_labels = (
    relationships_prepared
    .iloc[relationship_test_idx]
    ["relationship_label"]
    .value_counts()
)

distribution_df = pd.DataFrame({

    "Train": train_labels,

    "Validation": val_labels,

    "Test": test_labels

}).fillna(0).astype(int)

display(
    distribution_df
)

# ============================================================
# 17. SAVE FEATURE DATASET
# ============================================================

features_path = os.path.join(
    DATA_DIR,
    "relationship_training_features_16000.csv"
)

relationships_prepared.to_csv(
    features_path,
    index=False
)

print("\n✅ Feature dataset saved:")
print(features_path)

# ============================================================
# 18. SAVE SPLIT INDICES
# ============================================================

split_indices_path = os.path.join(
    DATA_DIR,
    "relationship_split_indices.npz"
)

np.savez(
    split_indices_path,

    train_idx=relationship_train_idx,

    val_idx=relationship_val_idx,

    test_idx=relationship_test_idx
)

print("\n✅ Split indices saved:")
print(split_indices_path)

# ============================================================
# 19. SAVE SPLIT INFORMATION
# ============================================================

split_info = {

    "total_pairs": int(total_pairs),

    "train_pairs": int(train_count),

    "validation_pairs": int(val_count),

    "test_pairs": int(test_count),

    "remaining_pairs": int(remaining),

    "feature_count": int(len(feature_columns)),

    "features": feature_columns,

    "grouping_method":
        "canonical_issue_pair",

    "random_state": 42,

    "same_issue_used_as_feature": False,

    "relationship_label_used_as_feature": False,

    "category_overlap_binary_used_as_feature": False

}

split_info_path = os.path.join(
    DATA_DIR,
    "relationship_split_info.json"
)

with open(
    split_info_path,
    "w"
) as f:

    json.dump(
        split_info,
        f,
        indent=2
    )

print("\n✅ Split information saved:")
print(split_info_path)

# ============================================================
# FINAL STATUS
# ============================================================

print("\n========================================")
print("🎉 STEP 10C CORRECTED COMPLETE")
print("========================================")

print(
    "Features:",
    len(feature_columns)
)

print(
    "Total pairs:",
    total_pairs
)

print(
    "Training:",
    train_count
)

print(
    "Validation:",
    val_count
)

print(
    "Test:",
    test_count
)

print(
    "Remaining:",
    remaining
)

print("\n✅ 20 backend-compatible features")
print("✅ Leakage fields excluded")
print("✅ Pair groups separated")
print("✅ All 16,000 pairs accounted for")

print("\nNext:")
print("Step 11/12 — Train Duplicate / Similar / Related / Independent classifier")

===== GrievanceIQ Training Progress =====
Step: 10 / 12
Part C: Corrected relationship feature engineering

Prepared dataset shape: (16000, 18)

===== RELATIONSHIP CLASSES =====

relationship_label
Independent    5000
Duplicate      4000
Related        3500
Similar        3500
Name: count, dtype: int64

Converting fine-grained categories...

===== FEATURE COUNT =====
Feature count: 20
✅ Exactly 20 features

Features:
01. semantic_similarity
02. location_score
03. temporal_score
04. duplicate_score
05. duplicate_flag
06. same_category
07. category_a_roads
08. category_a_water_supply
09. category_a_electricity
10. category_a_drainage
11. category_a_waste_management
12. category_a_public_infrastructure
13. category_a_other
14. category_b_roads
15. category_b_water_supply
16. category_b_electricity
17. category_b_drainage
18. category_b_waste_management
19. category_b_public_infrastructure
20. category_b_other

===== LEAKAGE CHECK =====
same_issue: NOT USED ✅
relationship_label: NOT USED ✅
category_overlap_binary: NOT USED ✅

===== MATRIX SHAPES =====
X shape: (16000, 20)
y shape: (16000,)
✅ Feature matrix correct

===== NUMERIC CHECK =====
NaN: 0
Infinite: 0
✅ No NaN
✅ No infinite values

========================================
BUILDING CANONICAL ISSUE-PAIR GROUPS
========================================
Unique issue-pair groups: 11999
Total relationship rows: 16000

========================================
PAIR-GROUP TRAIN / VALIDATION / TEST SPLIT
========================================

===== RELATIONSHIP SPLIT COUNTS =====
Total pairs:       16000
Training pairs:    11134
Validation pairs:  2446
Test pairs:        2420
Remaining pairs:   0

===== PERCENTAGES =====
Training:   69.59%
Validation: 15.29%
Test:       15.12%

✅ All 16,000 relationship pairs accounted for

===== PAIR-GROUP LEAKAGE CHECK =====
Train ↔ Validation: 0
Train ↔ Test: 0
Validation ↔ Test: 0

✅ No exact issue-pair group leakage

===== LABEL DISTRIBUTION =====

                    Train  Validation  Test
relationship_label
Duplicate            2736         616   648
Independent          3527         735   738
Related              2458         534   508
Similar              2413         561   526

✅ Feature dataset saved:
/content/drive/MyDrive/GrievanceIQ Dataset/relationship_training_features_16000.csv

✅ Split indices saved:
/content/drive/MyDrive/GrievanceIQ Dataset/relationship_split_indices.npz

✅ Split information saved:
/content/drive/MyDrive/GrievanceIQ Dataset/relationship_split_info.json

========================================
🎉 STEP 10C CORRECTED COMPLETE
========================================
Features: 20
Total pairs: 16000
Training: 11134
Validation: 2446
Test: 2420
Remaining: 0

✅ 20 backend-compatible features
✅ Leakage fields excluded
✅ Pair groups separated
✅ All 16,000 pairs accounted for

Next:
Step 11/12 — Train Duplicate / Similar / Related / Independent classifier

In [ ]:
# @title 🤖 Step 11/12A — Prepare Relationship Model Training Data

import os
import json
import numpy as np
import pandas as pd

print("===== GrievanceIQ Training Progress =====")
print("Step: 11 / 12")
print("Part A: Prepare backend-compatible Random Forest training data")
print()

# ============================================================
# 1. MAKE SURE FEATURES ARE AVAILABLE
# ============================================================

if "X_relationship" not in locals():

    print("X_relationship not found in memory.")
    print("Loading saved relationship feature dataset...")

    feature_file = os.path.join(
        DATA_DIR,
        "relationship_training_features_16000.csv"
    )

    relationship_features_df = pd.read_csv(
        feature_file
    )

    # Recreate exact feature list
    feature_columns = [
        "semantic_similarity",
        "location_score",
        "temporal_score",
        "duplicate_score",
        "duplicate_flag",
        "same_category",
        "category_a_roads",
        "category_a_water_supply",
        "category_a_electricity",
        "category_a_drainage",
        "category_a_waste_management",
        "category_a_public_infrastructure",
        "category_a_other",
        "category_b_roads",
        "category_b_water_supply",
        "category_b_electricity",
        "category_b_drainage",
        "category_b_waste_management",
        "category_b_public_infrastructure",
        "category_b_other"
    ]

    X_relationship = (
        relationship_features_df[
            feature_columns
        ]
        .astype(np.float32)
        .values
    )

    labels_raw = (
        relationship_features_df[
            "relationship_label"
        ]
        .astype(str)
        .values
    )

else:

    print("✅ X_relationship already available")

# ============================================================
# 2. LOAD SPLIT INDICES IF NECESSARY
# ============================================================

if (
    "relationship_train_idx" not in locals()
    or
    "relationship_val_idx" not in locals()
    or
    "relationship_test_idx" not in locals()
):

    print("\nSplit indices not found in memory.")
    print("Loading saved split indices...")

    split_file = os.path.join(
        DATA_DIR,
        "relationship_split_indices.npz"
    )

    split_data = np.load(
        split_file
    )

    relationship_train_idx = (
        split_data["train_idx"]
    )

    relationship_val_idx = (
        split_data["val_idx"]
    )

    relationship_test_idx = (
        split_data["test_idx"]
    )

# ============================================================
# 3. LOAD LABELS
# ============================================================

relationship_features_path = os.path.join(
    DATA_DIR,
    "relationship_training_features_16000.csv"
)

relationship_features_df = pd.read_csv(
    relationship_features_path
)

labels_raw = (
    relationship_features_df[
        "relationship_label"
    ]
    .astype(str)
    .values
)

# Existing backend label order
RELATIONSHIP_LABELS = [
    "Duplicate",
    "Similar",
    "Related",
    "Independent"
]

label_to_index = {
    label: index
    for index, label
    in enumerate(RELATIONSHIP_LABELS)
}

y_relationship = np.array([
    label_to_index[label]
    for label in labels_raw
], dtype=np.int32)

# ============================================================
# 4. CREATE TRAIN / VALIDATION / TEST ARRAYS
# ============================================================

X_train_rel = (
    X_relationship[
        relationship_train_idx
    ]
)

y_train_rel = (
    y_relationship[
        relationship_train_idx
    ]
)

X_val_rel = (
    X_relationship[
        relationship_val_idx
    ]
)

y_val_rel = (
    y_relationship[
        relationship_val_idx
    ]
)

X_test_rel = (
    X_relationship[
        relationship_test_idx
    ]
)

y_test_rel = (
    y_relationship[
        relationship_test_idx
    ]
)

# ============================================================
# 5. VERIFY COUNTS
# ============================================================

print("===== DATA COUNTS =====")

print(
    "Total pairs:      ",
    len(X_relationship)
)

print(
    "Training pairs:   ",
    len(X_train_rel)
)

print(
    "Validation pairs: ",
    len(X_val_rel)
)

print(
    "Test pairs:       ",
    len(X_test_rel)
)

accounted = (
    len(X_train_rel)
    +
    len(X_val_rel)
    +
    len(X_test_rel)
)

print(
    "Remaining pairs:  ",
    len(X_relationship) - accounted
)

assert len(X_relationship) == 16000
assert len(X_train_rel) == 11134
assert len(X_val_rel) == 2446
assert len(X_test_rel) == 2420

assert (
    len(X_relationship) - accounted
) == 0

print("\n✅ All 16,000 relationship pairs accounted for")

# ============================================================
# 6. VERIFY FEATURES
# ============================================================

print("\n===== FEATURE VERIFICATION =====")

print(
    "Training feature matrix:",
    X_train_rel.shape
)

print(
    "Validation feature matrix:",
    X_val_rel.shape
)

print(
    "Test feature matrix:",
    X_test_rel.shape
)

assert X_train_rel.shape[1] == 20
assert X_val_rel.shape[1] == 20
assert X_test_rel.shape[1] == 20

print("✅ Exactly 20 features")

# ============================================================
# 7. VERIFY LABELS
# ============================================================

print("\n===== LABEL VERIFICATION =====")

for index, label in enumerate(
    RELATIONSHIP_LABELS
):

    train_count = int(
        (y_train_rel == index).sum()
    )

    val_count = int(
        (y_val_rel == index).sum()
    )

    test_count = int(
        (y_test_rel == index).sum()
    )

    print(
        f"{label}: "
        f"Train={train_count}, "
        f"Validation={val_count}, "
        f"Test={test_count}"
    )

print("\n✅ Four-class target ready")

# ============================================================
# 8. CREATE MODEL WORK DIRECTORY
# ============================================================

MODEL_DIR = os.path.join(
    DATA_DIR,
    "trained_models"
)

os.makedirs(
    MODEL_DIR,
    exist_ok=True
)

# ============================================================
# 9. SAVE JSON PAYLOAD FOR NODE
# ============================================================

payload = {

    "labels": RELATIONSHIP_LABELS,

    "features": feature_columns,

    "X_train": X_train_rel.tolist(),

    "y_train": y_train_rel.tolist(),

    "X_val": X_val_rel.tolist(),

    "y_val": y_val_rel.tolist(),

    "X_test": X_test_rel.tolist(),

    "y_test": y_test_rel.tolist()
}

payload_path = os.path.join(
    MODEL_DIR,
    "relationship_training_payload.json"
)

with open(
    payload_path,
    "w"
) as f:

    json.dump(
        payload,
        f
    )

print("\n✅ Node training payload saved:")
print(payload_path)

print("\nPayload sizes:")
print("Train:", len(X_train_rel))
print("Validation:", len(X_val_rel))
print("Test:", len(X_test_rel))

print("\n🎉 STEP 11A COMPLETE")
print("Training pairs ready:", len(X_train_rel))
print("Validation pairs ready:", len(X_val_rel))
print("Test pairs ready:", len(X_test_rel))
print("Remaining:", 0)
print("Next: Step 11B — Train backend-compatible Random Forest")

===== GrievanceIQ Training Progress =====
Step: 11 / 12
Part A: Prepare backend-compatible Random Forest training data

✅ X_relationship already available
===== DATA COUNTS =====
Total pairs:       16000
Training pairs:    11134
Validation pairs:  2446
Test pairs:        2420
Remaining pairs:   0

✅ All 16,000 relationship pairs accounted for

===== FEATURE VERIFICATION =====
Training feature matrix: (11134, 20)
Validation feature matrix: (2446, 20)
Test feature matrix: (2420, 20)
✅ Exactly 20 features

===== LABEL VERIFICATION =====
Duplicate: Train=2736, Validation=616, Test=648
Similar: Train=2413, Validation=561, Test=526
Related: Train=2458, Validation=534, Test=508
Independent: Train=3527, Validation=735, Test=738

✅ Four-class target ready

✅ Node training payload saved:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/relationship_training_payload.json

Payload sizes:
Train: 11134
Validation: 2446
Test: 2420

🎉 STEP 11A COMPLETE
Training pairs ready: 11134
Validation pairs ready: 2446
Test pairs ready: 2420
Remaining: 0
Next: Step 11B — Train backend-compatible Random Forest

In [ ]:
# @title 📦 Step 11/12B — Install Backend Random Forest

!npm install ml-random-forest@2.1.0

print("✅ ml-random-forest 2.1.0 installed")

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋
added 17 packages in 3s
⠋npm notice
npm notice New major version of npm available! 10.8.2 -> 12.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v12.2.0
npm notice To update run: npm install -g npm@12.2.0
npm notice
⠋✅ ml-random-forest 2.1.0 installed

In [ ]:
# @title 🌲 Step 11C — FAST Backend-Compatible Relationship Random Forest

import os
import json
import subprocess
import textwrap

# ============================================================
# CONFIGURATION
# ============================================================

MODEL_DIR = os.path.join(
    DATA_DIR,
    "trained_models"
)

payload_path = os.path.join(
    MODEL_DIR,
    "relationship_training_payload.json"
)

node_script_path = (
    "/content/"
    "train_grievanceiq_relationship_model_fast.js"
)

model_output_path = os.path.join(
    MODEL_DIR,
    "relationship_model.json"
)

metadata_output_path = os.path.join(
    MODEL_DIR,
    "relationship_model_metadata.json"
)

predictions_output_path = os.path.join(
    MODEL_DIR,
    "relationship_predictions.json"
)

# ============================================================
# FAST MODEL SETTINGS
# ============================================================

N_ESTIMATORS = 30
MAX_FEATURES = 0.5
SEED = 42
REPLACEMENT = True
USE_SAMPLE_BAGGING = True

# ============================================================
# NODE.JS TRAINING SCRIPT
# ============================================================

script = r'''
const fs = require("fs");

const {
    RandomForestClassifier
} = require("ml-random-forest");

const payloadPath = process.argv[2];
const modelPath = process.argv[3];
const metadataPath = process.argv[4];
const predictionsPath = process.argv[5];

const N_ESTIMATORS = 30;
const MAX_FEATURES = 0.5;
const SEED = 42;
const REPLACEMENT = true;
const USE_SAMPLE_BAGGING = true;

const LABELS = [
    "Duplicate",
    "Similar",
    "Related",
    "Independent"
];

const payload = JSON.parse(
    fs.readFileSync(
        payloadPath,
        "utf8"
    )
);

const features = payload.features;

const XTrain = payload.X_train;
const yTrain = payload.y_train;

const XVal = payload.X_val;
const yVal = payload.y_val;

const XTest = payload.X_test;
const yTest = payload.y_test;

function evaluate(yTrue, yPred, numClasses) {

    const confusion = Array.from(
        { length: numClasses },
        () => new Array(numClasses).fill(0)
    );

    for (
        let i = 0;
        i < yTrue.length;
        i++
    ) {
        confusion[
            yTrue[i]
        ][
            yPred[i]
        ]++;
    }

    let correct = 0;

    for (
        let c = 0;
        c < numClasses;
        c++
    ) {
        correct += confusion[c][c];
    }

    const accuracy =
        correct / yTrue.length;

    const perClass = [];

    for (
        let c = 0;
        c < numClasses;
        c++
    ) {

        const tp =
            confusion[c][c];

        let fp = 0;
        let fn = 0;

        for (
            let j = 0;
            j < numClasses;
            j++
        ) {

            if (j !== c) {

                fp +=
                    confusion[j][c];

                fn +=
                    confusion[c][j];
            }
        }

        const precision =
            (tp + fp) > 0
                ? tp / (tp + fp)
                : 0;

        const recall =
            (tp + fn) > 0
                ? tp / (tp + fn)
                : 0;

        const f1 =
            (precision + recall) > 0
                ? (
                    2 *
                    precision *
                    recall
                  ) /
                  (
                    precision +
                    recall
                  )
                : 0;

        perClass.push({

            label:
                LABELS[c],

            precision:
                Number(
                    precision.toFixed(4)
                ),

            recall:
                Number(
                    recall.toFixed(4)
                ),

            f1:
                Number(
                    f1.toFixed(4)
                ),

            support:
                tp + fn
        });
    }

    return {

        accuracy:
            Number(
                accuracy.toFixed(4)
            ),

        confusionMatrix:
            confusion,

        perClass
    };
}

console.log(
    "========================================"
);

console.log(
    "GrievanceIQ Relationship Random Forest"
);

console.log(
    "FAST BACKEND-COMPATIBLE VERSION"
);

console.log(
    "========================================"
);

console.log("");

console.log(
    "Training pairs:",
    XTrain.length
);

console.log(
    "Validation pairs:",
    XVal.length
);

console.log(
    "Test pairs:",
    XTest.length
);

console.log(
    "Features:",
    features.length
);

console.log(
    "Classes:",
    LABELS.length
);

console.log("");

console.log(
    "===== MODEL CONFIGURATION ====="
);

console.log(
    "Trees:",
    N_ESTIMATORS
);

console.log(
    "Max features:",
    MAX_FEATURES
);

console.log(
    "Replacement:",
    REPLACEMENT
);

console.log(
    "Sample bagging:",
    USE_SAMPLE_BAGGING
);

console.log(
    "Seed:",
    SEED
);

console.log("");

console.log(
    "===== TRAINING ====="
);

console.log(
    "Progress:"
);

console.log(
    "1/4 Dataset loaded ✅"
);

console.log(
    "2/4 20-feature matrix ready ✅"
);

console.log(
    "3/4 Training Random Forest..."
);

const classifier =
    new RandomForestClassifier({

        nEstimators:
            N_ESTIMATORS,

        maxFeatures:
            MAX_FEATURES,

        replacement:
            REPLACEMENT,

        seed:
            SEED,

        useSampleBagging:
            USE_SAMPLE_BAGGING
    });

const startTime =
    Date.now();

classifier.train(
    XTrain,
    yTrain
);

const trainingSeconds =
    (
        Date.now()
        -
        startTime
    ) / 1000;

console.log(
    "4/4 Training complete ✅"
);

console.log(
    "Training time:",
    trainingSeconds.toFixed(2),
    "seconds"
);

console.log("");

console.log(
    "===== VALIDATION ====="
);

const yValPred =
    classifier.predict(
        XVal
    );

const validationMetrics =
    evaluate(
        yVal,
        yValPred,
        LABELS.length
    );

console.log(
    "Validation predictions:",
    yValPred.length,
    "/",
    yVal.length
);

console.log(
    "Validation accuracy:",
    validationMetrics.accuracy
);

for (
    const result
    of validationMetrics.perClass
) {

    console.log(
        result.label,
        "F1=",
        result.f1
    );
}

console.log("");

console.log(
    "===== FINAL TEST ====="
);

const yTestPred =
    classifier.predict(
        XTest
    );

const testMetrics =
    evaluate(
        yTest,
        yTestPred,
        LABELS.length
    );

console.log(
    "Test predictions:",
    yTestPred.length,
    "/",
    yTest.length
);

console.log(
    "Test accuracy:",
    testMetrics.accuracy
);

console.log("");

console.log(
    "===== TEST PER-CLASS RESULTS ====="
);

for (
    const result
    of testMetrics.perClass
) {

    console.log(
        result.label.padEnd(15),
        "Precision=",
        result.precision.toFixed(4),
        "Recall=",
        result.recall.toFixed(4),
        "F1=",
        result.f1.toFixed(4),
        "Support=",
        result.support
    );
}

console.log("");

console.log(
    "===== TEST CONFUSION MATRIX ====="
);

console.log(
    "Rows = Actual"
);

console.log(
    "Columns = Predicted"
);

console.log(
    "             ",
    LABELS.join(" | ")
);

for (
    let i = 0;
    i < testMetrics.confusionMatrix.length;
    i++
) {

    console.log(
        LABELS[i].padEnd(13),
        testMetrics.confusionMatrix[i]
            .join(" | ")
    );
}

console.log("");

console.log(
    "===== SAVING MODEL ====="
);

const modelJson =
    classifier.toJSON();

fs.writeFileSync(
    modelPath,
    JSON.stringify(
        modelJson
    ),
    "utf8"
);

console.log(
    "✅ Model saved:",
    modelPath
);

const metadata = {

    version:
        "2.0.0-fast",

    phase:
        3,

    trainingDate:
        new Date().toISOString(),

    datasetSize:
        XTrain.length +
        XVal.length +
        XTest.length,

    trainSize:
        XTrain.length,

    validationSize:
        XVal.length,

    testSize:
        XTest.length,

    featureCount:
        features.length,

    features:

        features,

    labels:

        LABELS,

    hyperparameters: {

        nEstimators:
            N_ESTIMATORS,

        maxFeatures:
            MAX_FEATURES,

        replacement:
            REPLACEMENT,

        useSampleBagging:
            USE_SAMPLE_BAGGING,

        seed:
            SEED
    },

    splitMethod:
        "canonical_issue_pair_group",

    leakageControls: {

        same_issue_used:
            false,

        relationship_label_used:
            false,

        pair_group_overlap:
            false
    },

    validationMetrics:
        validationMetrics,

    testMetrics:
        testMetrics,

    trainingTimeSeconds:
        trainingSeconds,

    notes:
        "Synthetic held-out evaluation. "
        +
        "Does not establish real-world generalization."
};

fs.writeFileSync(
    metadataPath,
    JSON.stringify(
        metadata,
        null,
        2
    ),
    "utf8"
);

console.log(
    "✅ Metadata saved:",
    metadataPath
);

const predictions = {

    labels:

        LABELS,

    validation: {

        y_true:
            yVal,

        y_pred:
            yValPred,

        metrics:
            validationMetrics
    },

    test: {

        y_true:
            yTest,

        y_pred:
            yTestPred,

        metrics:
            testMetrics
    }
};

fs.writeFileSync(
    predictionsPath,
    JSON.stringify(
        predictions,
        null,
        2
    ),
    "utf8"
);

console.log(
    "✅ Predictions saved:",
    predictionsPath
);

console.log("");

console.log(
    "========================================"
);

console.log(
    "🎉 STEP 11C COMPLETE"
);

console.log(
    "========================================"
);

console.log(
    "Training:",
    XTrain.length,
    "/",
    XTrain.length
);

console.log(
    "Validation:",
    XVal.length,
    "/",
    XVal.length
);

console.log(
    "Test:",
    XTest.length,
    "/",
    XTest.length
);

console.log(
    "Remaining:",
    0
);
'''

# ============================================================
# WRITE SCRIPT
# ============================================================

with open(
    node_script_path,
    "w"
) as f:

    f.write(script)

print(
    "✅ New fast Node training script created:"
)

print(
    node_script_path
)

print("")

print(
    "Starting FAST backend-compatible training..."
)

print(
    "Expected: a few minutes rather than the previous long run."
)

print("")

# ============================================================
# RUN WITHOUT CAPTURING OUTPUT
# ============================================================
# This lets Node's output appear immediately in Colab.

result = subprocess.run(
    [
        "node",
        node_script_path,
        payload_path,
        model_output_path,
        metadata_output_path,
        predictions_output_path
    ]
)

# ============================================================
# CHECK RESULT
# ============================================================

if result.returncode != 0:

    raise RuntimeError(
        f"Node training failed with exit code "
        f"{result.returncode}"
    )

# ============================================================
# CHECK FILES
# ============================================================

print("")
print(
    "===== FINAL FILE CHECK ====="
)

for file_path in [

    model_output_path,

    metadata_output_path,

    predictions_output_path

]:

    if not os.path.exists(
        file_path
    ):

        raise FileNotFoundError(
            file_path
        )

    size_kb = (
        os.path.getsize(
            file_path
        )
        / 1024
    )

    print(
        f"✅ {os.path.basename(file_path)} "
        f"({size_kb:.1f} KB)"
    )

print("")
print(
    "🎉 STEP 11C SUCCESSFULLY COMPLETED"
)

print(
    "Training pairs: 11134 / 11134"
)

print(
    "Validation pairs: 2446 / 2446"
)

print(
    "Test pairs: 2420 / 2420"
)

print(
    "Remaining: 0"
)

✅ New fast Node training script created:
/content/train_grievanceiq_relationship_model_fast.js

Starting FAST backend-compatible training...
Expected: a few minutes rather than the previous long run.


===== FINAL FILE CHECK =====
✅ relationship_model.json (1531.5 KB)
✅ relationship_model_metadata.json (3.1 KB)
✅ relationship_predictions.json (87.8 KB)

🎉 STEP 11C SUCCESSFULLY COMPLETED
Training pairs: 11134 / 11134
Validation pairs: 2446 / 2446
Test pairs: 2420 / 2420
Remaining: 0

In [ ]:
# @title ✅ Step 12/12A — Final Model Verification

import os
import json
import joblib

MODEL_DIR = os.path.join(
    DATA_DIR,
    "trained_models"
)

print("========================================")
print("GrievanceIQ FINAL MODEL VERIFICATION")
print("========================================")
print()

# ------------------------------------------------------------
# EXPECTED FILES
# ------------------------------------------------------------

required_files = [
    "multilabel_classifier.joblib",
    "issue_labels.json",
    "multilabel_training_config.json",
    "multilabel_evaluation_metrics.json",
    "multilabel_thresholds.csv",
    "multilabel_classification_report.csv",
    "multilabel_test_predictions.csv",
    "relationship_model.json",
    "relationship_model_metadata.json",
    "relationship_predictions.json"
]

print("Checking final files...\n")

missing = []

for filename in required_files:

    path = os.path.join(
        MODEL_DIR,
        filename
    )

    if os.path.exists(path):

        size_kb = os.path.getsize(path) / 1024

        print(
            f"✅ {filename:<45} "
            f"{size_kb:.1f} KB"
        )

    else:

        print(
            f"❌ MISSING: {filename}"
        )

        missing.append(filename)

if missing:

    raise FileNotFoundError(
        "Missing final files: "
        + str(missing)
    )

print("\n✅ All required model artifacts exist")

# ------------------------------------------------------------
# LOAD MULTI-LABEL MODEL
# ------------------------------------------------------------

print("\n========================================")
print("MULTI-LABEL MODEL CHECK")
print("========================================")

multilabel_path = os.path.join(
    MODEL_DIR,
    "multilabel_classifier.joblib"
)

multilabel_model = joblib.load(
    multilabel_path
)

print(
    "Loaded object type:",
    type(multilabel_model)
)

print(
    "Number of trained label models:",
    len(multilabel_model)
)

assert len(multilabel_model) == 9

print("✅ 9 issue models found")

# ------------------------------------------------------------
# CHECK LABEL FILE
# ------------------------------------------------------------

labels_path = os.path.join(
    MODEL_DIR,
    "issue_labels.json"
)

with open(labels_path, "r") as f:
    labels = json.load(f)

print("\nIssue labels:")

for i, label in enumerate(labels, 1):
    print(
        f"{i}/9  {label}"
    )

assert len(labels) == 9

print("✅ Label mapping verified")

# ------------------------------------------------------------
# CHECK RELATIONSHIP MODEL JSON
# ------------------------------------------------------------

print("\n========================================")
print("RELATIONSHIP MODEL CHECK")
print("========================================")

relationship_path = os.path.join(
    MODEL_DIR,
    "relationship_model.json"
)

with open(
    relationship_path,
    "r"
) as f:

    relationship_model_json = json.load(f)

print(
    "JSON loaded successfully ✅"
)

print(
    "JSON top-level keys:",
    list(relationship_model_json.keys())
)

# ------------------------------------------------------------
# CHECK METADATA
# ------------------------------------------------------------

metadata_path = os.path.join(
    MODEL_DIR,
    "relationship_model_metadata.json"
)

with open(
    metadata_path,
    "r"
) as f:

    metadata = json.load(f)

print("\nRelationship metadata:")

print(
    "Training pairs:",
    metadata["trainSize"]
)

print(
    "Validation pairs:",
    metadata["validationSize"]
)

print(
    "Test pairs:",
    metadata["testSize"]
)

print(
    "Features:",
    metadata["featureCount"]
)

print(
    "Labels:",
    metadata["labels"]
)

assert metadata["trainSize"] == 11134
assert metadata["validationSize"] == 2446
assert metadata["testSize"] == 2420
assert metadata["featureCount"] == 20

print("\n✅ Relationship metadata verified")

print("\n========================================")
print("🎉 STEP 12A COMPLETE")
print("========================================")

print("Multi-label models: 9/9 ✅")
print("Relationship model: 1/1 ✅")
print("Required files: complete ✅")
print("Remaining files: 0")

========================================
GrievanceIQ FINAL MODEL VERIFICATION
========================================

Checking final files...

✅ multilabel_classifier.joblib                  30.7 KB
✅ issue_labels.json                             0.2 KB
✅ multilabel_training_config.json               0.6 KB
✅ multilabel_evaluation_metrics.json            1.1 KB
✅ multilabel_thresholds.csv                     0.5 KB
✅ multilabel_classification_report.csv          0.9 KB
✅ multilabel_test_predictions.csv               274.4 KB
✅ relationship_model.json                       1531.5 KB
✅ relationship_model_metadata.json              3.1 KB
✅ relationship_predictions.json                 87.8 KB

✅ All required model artifacts exist

========================================
MULTI-LABEL MODEL CHECK
========================================
Loaded object type: <class 'dict'>
Number of trained label models: 9
✅ 9 issue models found

Issue labels:
1/9  road_damage_flag
2/9  roadside_flooding_flag
3/9  water_leakage_flag
4/9  electric_pole_flag
5/9  streetlight_flag
6/9  traffic_signal_flag
7/9  garbage_flag
8/9  tree_hazard_flag
9/9  drainage_flag
✅ Label mapping verified

========================================
RELATIONSHIP MODEL CHECK
========================================
JSON loaded successfully ✅
JSON top-level keys: ['baseModel', 'name']

Relationship metadata:
Training pairs: 11134
Validation pairs: 2446
Test pairs: 2420
Features: 20
Labels: ['Duplicate', 'Similar', 'Related', 'Independent']

✅ Relationship metadata verified

========================================
🎉 STEP 12A COMPLETE
========================================
Multi-label models: 9/9 ✅
Relationship model: 1/1 ✅
Required files: complete ✅
Remaining files: 0

In [ ]:
# @title 🔌 Step 12/12B — Backend Compatibility Test

import os
import json
import subprocess

MODEL_DIR = os.path.join(
    DATA_DIR,
    "trained_models"
)

relationship_model_path = os.path.join(
    MODEL_DIR,
    "relationship_model.json"
)

node_test_path = "/content/test_grievanceiq_relationship_model.js"

script = r'''
const fs = require("fs");

const {
    RandomForestClassifier
} = require("ml-random-forest");

const modelPath = process.argv[2];

console.log("========================================");
console.log("GrievanceIQ Backend Compatibility Test");
console.log("========================================");

console.log("");
console.log("Model:");
console.log(modelPath);

if (!fs.existsSync(modelPath)) {
    throw new Error("Model file does not exist");
}

const modelJson = JSON.parse(
    fs.readFileSync(modelPath, "utf8")
);

console.log("✅ JSON parsed");

const classifier =
    RandomForestClassifier.load(
        modelJson
    );

console.log(
    "✅ RandomForestClassifier loaded"
);

const features = new Array(20).fill(0);

console.log(
    "Test feature vector length:",
    features.length
);

const prediction =
    classifier.predict([
        features
    ]);

console.log(
    "Prediction result:",
    prediction
);

if (
    !Array.isArray(prediction) ||
    prediction.length !== 1
) {
    throw new Error(
        "Unexpected prediction format"
    );
}

const predictedClass =
    prediction[0];

if (
    predictedClass < 0 ||
    predictedClass > 3
) {
    throw new Error(
        "Invalid relationship class"
    );
}

const labels = [
    "Duplicate",
    "Similar",
    "Related",
    "Independent"
];

console.log(
    "Predicted relationship:",
    labels[predictedClass]
);

console.log("");
console.log(
    "🎉 BACKEND COMPATIBILITY PASSED"
);
'''

with open(
    node_test_path,
    "w"
) as f:

    f.write(script)

result = subprocess.run(
    [
        "node",
        node_test_path,
        relationship_model_path
    ],
    capture_output=True,
    text=True
)

print(result.stdout)

if result.returncode != 0:

    print(result.stderr)

    raise RuntimeError(
        "Backend compatibility test failed"
    )

print("\n✅ Step 12B complete")
print("relationship_model.json is loadable by Node.js")
print("Remaining: 0")

========================================
GrievanceIQ Backend Compatibility Test
========================================

Model:
/content/drive/MyDrive/GrievanceIQ Dataset/trained_models/relationship_model.json
✅ JSON parsed
✅ RandomForestClassifier loaded
Test feature vector length: 20
Prediction result: [ 3 ]
Predicted relationship: Independent

🎉 BACKEND COMPATIBILITY PASSED


✅ Step 12B complete
relationship_model.json is loadable by Node.js
Remaining: 0

In [ ]:
# @title 📦 Step 12C/12 — Create Final GrievanceIQ Download Package

import os
import zipfile
from datetime import datetime

MODEL_DIR = "/content/drive/MyDrive/GrievanceIQ Dataset/trained_models"

FINAL_DIR = "/content/GrievanceIQ_Final_Package"
os.makedirs(FINAL_DIR, exist_ok=True)

ZIP_PATH = "/content/GrievanceIQ_Final_Model_Package.zip"

print("========================================")
print("GrievanceIQ Final Packaging")
print("========================================")
print()

# ============================================================
# FILES
# ============================================================

files_to_copy = [
    "multilabel_classifier.joblib",
    "issue_labels.json",
    "multilabel_training_config.json",
    "multilabel_evaluation_metrics.json",
    "multilabel_thresholds.csv",
    "multilabel_classification_report.csv",
    "multilabel_test_predictions.csv",
    "relationship_model.json",
    "relationship_model_metadata.json",
    "relationship_predictions.json"
]

# ============================================================
# COPY INTO PACKAGE DIRECTORY
# ============================================================

import shutil

print("Packaging files...\n")

completed = 0

for filename in files_to_copy:

    source = os.path.join(
        MODEL_DIR,
        filename
    )

    destination = os.path.join(
        FINAL_DIR,
        filename
    )

    if not os.path.exists(source):
        raise FileNotFoundError(
            f"Missing: {source}"
        )

    shutil.copy2(
        source,
        destination
    )

    completed += 1

    print(
        f"{completed}/{len(files_to_copy)} ✅ "
        f"{filename} | "
        f"Remaining: "
        f"{len(files_to_copy) - completed}"
    )

# ============================================================
# CREATE README
# ============================================================

readme = f"""
GRIEVANCEIQ FINAL MODEL PACKAGE
================================

Created: {datetime.now().isoformat()}

MULTI-LABEL MODEL
-----------------
Model:
multilabel_classifier.joblib

Embedding:
sentence-transformers/all-MiniLM-L6-v2

Embedding dimension:
384

Labels:
1. road_damage_flag
2. roadside_flooding_flag
3. water_leakage_flag
4. electric_pole_flag
5. streetlight_flag
6. traffic_signal_flag
7. garbage_flag
8. tree_hazard_flag
9. drainage_flag

Dataset:
6000 synthetic complaints

Train:
4196

Validation:
904

Test:
900


RELATIONSHIP MODEL
------------------
Model:
relationship_model.json

Classes:
1. Duplicate
2. Similar
3. Related
4. Independent

Features:
20

Dataset:
16000 synthetic complaint pairs

Train:
11134

Validation:
2446

Test:
2420

Training:
Random Forest
30 trees
maxFeatures = 0.5
seed = 42


GITHUB INTEGRATION
------------------

Relationship model:

relationship_model.json
    ->
backend/models/relationship/model.json

relationship_model_metadata.json
    ->
backend/models/relationship/metadata.json

IMPORTANT
---------

The multilabel_classifier.joblib file is a Python/scikit-learn
model. It cannot be directly loaded by the existing Node.js
backend using require().

Use a Python inference service or convert/integrate the model
through ONNX before connecting it to the Node.js application.

The relationship Random Forest model is already serialized in
the format used by the current Node.js backend.

Research/evaluation files are included for documentation and
evaluation. Do not treat synthetic test performance as
real-world accuracy.
"""

readme_path = os.path.join(
    FINAL_DIR,
    "README.txt"
)

with open(
    readme_path,
    "w"
) as f:
    f.write(readme)

print("\n✅ README created")

# ============================================================
# CREATE GITHUB STRUCTURE
# ============================================================

github_dir = os.path.join(
    FINAL_DIR,
    "github_integration"
)

github_relationship_dir = os.path.join(
    github_dir,
    "backend",
    "models",
    "relationship"
)

os.makedirs(
    github_relationship_dir,
    exist_ok=True
)

# Copy relationship files into exact backend names

shutil.copy2(
    os.path.join(
        MODEL_DIR,
        "relationship_model.json"
    ),
    os.path.join(
        github_relationship_dir,
        "model.json"
    )
)

shutil.copy2(
    os.path.join(
        MODEL_DIR,
        "relationship_model_metadata.json"
    ),
    os.path.join(
        github_relationship_dir,
        "metadata.json"
    )
)

print("\n✅ GitHub relationship-model folder created")

# ============================================================
# ZIP EVERYTHING
# ============================================================

print("\n========================================")
print("Creating ZIP")
print("========================================")

if os.path.exists(ZIP_PATH):
    os.remove(ZIP_PATH)

with zipfile.ZipFile(
    ZIP_PATH,
    "w",
    zipfile.ZIP_DEFLATED
) as zip_file:

    for root, dirs, files in os.walk(
        FINAL_DIR
    ):

        for filename in files:

            full_path = os.path.join(
                root,
                filename
            )

            relative_path = os.path.relpath(
                full_path,
                FINAL_DIR
            )

            zip_file.write(
                full_path,
                relative_path
            )

print("\n✅ ZIP created")

size_mb = (
    os.path.getsize(ZIP_PATH)
    /
    (1024 * 1024)
)

print(
    f"Package size: {size_mb:.2f} MB"
)

print(
    "Files packaged:",
    completed
)

print(
    "Remaining:",
    0
)

print("\nPackage path:")
print(ZIP_PATH)

print("\n🎉 STEP 12C COMPLETE")
print("Next: Step 12D — Download")

========================================
GrievanceIQ Final Packaging
========================================

Packaging files...

1/10 ✅ multilabel_classifier.joblib | Remaining: 9
2/10 ✅ issue_labels.json | Remaining: 8
3/10 ✅ multilabel_training_config.json | Remaining: 7
4/10 ✅ multilabel_evaluation_metrics.json | Remaining: 6
5/10 ✅ multilabel_thresholds.csv | Remaining: 5
6/10 ✅ multilabel_classification_report.csv | Remaining: 4
7/10 ✅ multilabel_test_predictions.csv | Remaining: 3
8/10 ✅ relationship_model.json | Remaining: 2
9/10 ✅ relationship_model_metadata.json | Remaining: 1
10/10 ✅ relationship_predictions.json | Remaining: 0

✅ README created

✅ GitHub relationship-model folder created

========================================
Creating ZIP
========================================

✅ ZIP created
Package size: 0.33 MB
Files packaged: 10
Remaining: 0

Package path:
/content/GrievanceIQ_Final_Model_Package.zip

🎉 STEP 12C COMPLETE
Next: Step 12D — Download

In [ ]:
# @title ⬇️ Step 12D/12 — Download Final GrievanceIQ Package

from google.colab import files

ZIP_PATH = "/content/GrievanceIQ_Final_Model_Package.zip"

print("========================================")
print("GrievanceIQ FINAL DOWNLOAD")
print("========================================")
print()

print("File:", ZIP_PATH)

files.download(
    ZIP_PATH
)

print("\n✅ Download started")
print("Remaining: 0")

print("\n🎉 GRIEVANCEIQ MODEL TRAINING COMPLETE")

========================================
GrievanceIQ FINAL DOWNLOAD
========================================

File: /content/GrievanceIQ_Final_Model_Package.zip

✅ Download started
Remaining: 0

🎉 GRIEVANCEIQ MODEL TRAINING COMPLETE